'use strict';

const fs = require('node:fs');
const path = require('node:path');

const runtimeDir = path.resolve(__dirname, '../userscript');

function readRuntime(name) {
  return fs.readFileSync(path.join(runtimeDir, name), 'utf8');
}

// Substitute generated values into an extracted runtime source. Each placeholder must occur
// exactly once: a missing one means the runtime drifted from the builder, and a repeated one
// means the substitution would be ambiguous. Either way the build should fail loudly rather
// than emit a userscript with an unreplaced `__ZOOPDOG_*__` token in it.
function renderRuntime(source, replacements) {
  let output = source;
  for (const [placeholder, value] of Object.entries(replacements)) {
    const parts = output.split(placeholder);
    if (parts.length !== 2) {
      throw new Error(
        `Runtime placeholder ${placeholder} must appear exactly once, found ${parts.length - 1}`
      );
    }
    output = parts.join(String(value));
  }
  if (/__ZOOPDOG_[A-Z_]+__/.test(output)) {
    throw new Error(`Unreplaced runtime placeholder: ${output.match(/__ZOOPDOG_[A-Z_]+__/)[0]}`);
  }
  return output;
}

// Emits `value` as `JSON.parse("...")` source. V8 parses a JSON string markedly faster than the
// same data written as an object literal (measured ~2x on the 5 MB popup dictionary), and the
// literal is at once a valid JS string and a valid JSON string, so `extractAssignedJson` below
// can read it back with the JSON primitives it already has.
function jsonParseLiteral(value) {
  return `JSON.parse(${JSON.stringify(JSON.stringify(value))})`;
}

// Generic JS-source-value-span scanning, used by `extractAssignedJson` to find where a
// `var NOM_MAP = {...}` / `var ZOO_DICTIONARY = {...}` assignment's value ends inside a
// generated userscript.
function skipJsoncTrivia(source, start) {
  let index = start;
  while (index < source.length) {
    if (/\s/.test(source[index])) {
      index++;
      continue;
    }
    if (source[index] === '/' && source[index + 1] === '/') {
      index += 2;
      while (index < source.length && source[index] !== '\n') index++;
      continue;
    }
    if (source[index] === '/' && source[index + 1] === '*') {
      const end = source.indexOf('*/', index + 2);
      if (end < 0) throw new Error('Unterminated JSONC block comment.');
      index = end + 2;
      continue;
    }
    break;
  }
  return index;
}

function readJsonStringEnd(source, start) {
  let escaped = false;
  for (let index = start + 1; index < source.length; index++) {
    const char = source[index];
    if (escaped) {
      escaped = false;
    } else if (char === '\\') {
      escaped = true;
    } else if (char === '"') {
      return index + 1;
    }
  }
  throw new Error('Unterminated JSON string.');
}

function readJsonValueEnd(source, start) {
  if (source[start] === '"') {
    return readJsonStringEnd(source, start);
  }
  let square = 0;
  let curly = 0;
  let index = start;
  while (index < source.length) {
    const char = source[index];
    if (char === '"') {
      index = readJsonStringEnd(source, index);
      continue;
    }
    if (char === '/' && (source[index + 1] === '/' || source[index + 1] === '*')) {
      index = skipJsoncTrivia(source, index);
      continue;
    }
    if (char === '[') square++;
    else if (char === ']') {
      square--;
      if (square === 0 && curly === 0) return index + 1;
    }
    else if (char === '{') curly++;
    else if (char === '}') {
      if (square === 0 && curly === 0) return index;
      curly--;
      if (square === 0 && curly === 0) return index + 1;
    } else if (char === ',' && square === 0 && curly === 0) {
      return index;
    }
    index++;
  }
  return index;
}

// Reads back a `var <variableName> = ...;` assignment written by `jsonParseLiteral` (or a plain
// object literal) from generated userscript source.
function extractAssignedJson(source, variableName) {
  const marker = `var ${variableName} =`;
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) throw new Error(`Missing generated ${variableName}.`);
  let start = markerIndex + marker.length;
  while (start < source.length && /\s/.test(source[start])) start++;
  const wrapper = 'JSON.parse(';
  if (source.startsWith(wrapper, start)) {
    const stringStart = start + wrapper.length;
    return JSON.parse(JSON.parse(source.slice(stringStart, readJsonStringEnd(source, stringStart))));
  }
  const end = readJsonValueEnd(source, start);
  return JSON.parse(source.slice(start, end));
}

// --- versioning ------------------------------------------------------------

// Tampermonkey installs an update only when the served @version compares greater than the
// installed one, so the stamp has to move whenever the generated bytes move — and has to stay
// put when they do not, or every rebuild would dirty a committed userscript for no reason.
const VERSION_PLACEHOLDER = '__ZOOPDOG_VERSION__';
const PENDING_VERSION = '0.0.0';
const VERSION_LINE = /^(\/\/ @version[ \t]+)(\S+)([ \t]*)$/m;

function readUserscriptVersion(source) {
  const match = source.match(VERSION_LINE);
  return match ? match[2] : null;
}

function setUserscriptVersion(source, version) {
  let seen = 0;
  const output = source.replace(new RegExp(VERSION_LINE.source, 'gm'), (whole, prefix, _old, suffix) => {
    seen += 1;
    return `${prefix}${version}${suffix}`;
  });
  if (seen !== 1) {
    throw new Error(`Userscript must declare @version exactly once, found ${seen}`);
  }
  return output;
}

// Dotted numeric comparison, the subset of Tampermonkey's version ordering these stamps use.
// A missing segment counts as 0, so 2026.09.05.1 sorts above 2026.09.05.
function compareVersions(left, right) {
  const a = String(left).split('.');
  const b = String(right).split('.');
  for (let index = 0; index < Math.max(a.length, b.length); index += 1) {
    const x = Number(a[index] ?? 0);
    const y = Number(b[index] ?? 0);
    if (!Number.isFinite(x) || !Number.isFinite(y)) {
      throw new Error(`Version segments must be numeric: ${left} vs ${right}`);
    }
    if (x !== y) {
      return x < y ? -1 : 1;
    }
  }
  return 0;
}

function versionDatestamp(now = new Date()) {
  const pad = (value) => String(value).padStart(2, '0');
  return `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}`;
}

// The build date is the readable stamp; a trailing counter only appears when a date is already
// taken, which keeps a second rebuild on the same day strictly newer than the first.
function nextUserscriptVersion(previousVersion, datestamp) {
  if (!previousVersion || compareVersions(datestamp, previousVersion) > 0) {
    return datestamp;
  }
  const segments = previousVersion.split('.');
  if (segments.length > 3 && Number.isInteger(Number(segments[segments.length - 1]))) {
    segments[segments.length - 1] = String(Number(segments[segments.length - 1]) + 1);
    return segments.join('.');
  }
  return `${previousVersion}.1`;
}

// Stamps the rendered userscript and writes it. The draft carries PENDING_VERSION, so the
// comparison against the committed file is a comparison of everything except the stamp.
function writeVersionedUserscript(targetPath, draft, now = new Date()) {
  const previous = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf8') : null;
  const previousVersion = previous ? readUserscriptVersion(previous) : null;
  const changed = !previousVersion ||
    setUserscriptVersion(previous, PENDING_VERSION) !== setUserscriptVersion(draft, PENDING_VERSION);
  const version = changed
    ? nextUserscriptVersion(previousVersion, versionDatestamp(now))
    : previousVersion;

  fs.writeFileSync(targetPath, setUserscriptVersion(draft, version), 'utf8');
  return {version, changed};
}

module.exports = {
  runtimeDir,
  readRuntime,
  renderRuntime,
  jsonParseLiteral,
  extractAssignedJson,
  VERSION_PLACEHOLDER,
  PENDING_VERSION,
  readUserscriptVersion,
  setUserscriptVersion,
  compareVersions,
  versionDatestamp,
  nextUserscriptVersion,
  writeVersionedUserscript
};
