'use strict';

const fs = require('node:fs');
const path = require('node:path');

const runtimeDir = path.resolve(__dirname, '../userscript');

function readRuntime(name) {
  return fs.readFileSync(path.join(runtimeDir, name), 'utf8');
}

// Substitute generated values into an extracted runtime source. Each placeholder must occur
// exactly once: a missing one means the runtime drifted from the builder, and a repeated one
// means the substitution would be ambiguous. Either way the build should fail loudly rather
// than emit a userscript with an unreplaced `__ZOOPDOG_*__` token in it.
function renderRuntime(source, replacements) {
  let output = source;
  for (const [placeholder, value] of Object.entries(replacements)) {
    const parts = output.split(placeholder);
    if (parts.length !== 2) {
      throw new Error(
        `Runtime placeholder ${placeholder} must appear exactly once, found ${parts.length - 1}`
      );
    }
    output = parts.join(String(value));
  }
  if (/__ZOOPDOG_[A-Z_]+__/.test(output)) {
    throw new Error(`Unreplaced runtime placeholder: ${output.match(/__ZOOPDOG_[A-Z_]+__/)[0]}`);
  }
  return output;
}

// --- versioning ------------------------------------------------------------

// Tampermonkey installs an update only when the served @version compares greater than the
// installed one, so the stamp has to move whenever the generated bytes move — and has to stay
// put when they do not, or every rebuild would dirty a committed userscript for no reason.
const VERSION_PLACEHOLDER = '__ZOOPDOG_VERSION__';
const PENDING_VERSION = '0.0.0';
const VERSION_LINE = /^(\/\/ @version[ \t]+)(\S+)([ \t]*)$/m;

function readUserscriptVersion(source) {
  const match = source.match(VERSION_LINE);
  return match ? match[2] : null;
}

function setUserscriptVersion(source, version) {
  let seen = 0;
  const output = source.replace(new RegExp(VERSION_LINE.source, 'gm'), (whole, prefix, _old, suffix) => {
    seen += 1;
    return `${prefix}${version}${suffix}`;
  });
  if (seen !== 1) {
    throw new Error(`Userscript must declare @version exactly once, found ${seen}`);
  }
  return output;
}

// Dotted numeric comparison, the subset of Tampermonkey's version ordering these stamps use.
// A missing segment counts as 0, so 2026.09.05.1 sorts above 2026.09.05.
function compareVersions(left, right) {
  const a = String(left).split('.');
  const b = String(right).split('.');
  for (let index = 0; index < Math.max(a.length, b.length); index += 1) {
    const x = Number(a[index] ?? 0);
    const y = Number(b[index] ?? 0);
    if (!Number.isFinite(x) || !Number.isFinite(y)) {
      throw new Error(`Version segments must be numeric: ${left} vs ${right}`);
    }
    if (x !== y) {
      return x < y ? -1 : 1;
    }
  }
  return 0;
}

function versionDatestamp(now = new Date()) {
  const pad = (value) => String(value).padStart(2, '0');
  return `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}`;
}

// The build date is the readable stamp; a trailing counter only appears when a date is already
// taken, which keeps a second rebuild on the same day strictly newer than the first.
function nextUserscriptVersion(previousVersion, datestamp) {
  if (!previousVersion || compareVersions(datestamp, previousVersion) > 0) {
    return datestamp;
  }
  const segments = previousVersion.split('.');
  if (segments.length > 3 && Number.isInteger(Number(segments[segments.length - 1]))) {
    segments[segments.length - 1] = String(Number(segments[segments.length - 1]) + 1);
    return segments.join('.');
  }
  return `${previousVersion}.1`;
}

// Stamps the rendered userscript and writes it. The draft carries PENDING_VERSION, so the
// comparison against the committed file is a comparison of everything except the stamp.
function writeVersionedUserscript(targetPath, draft, now = new Date()) {
  const previous = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf8') : null;
  const previousVersion = previous ? readUserscriptVersion(previous) : null;
  const changed = !previousVersion ||
    setUserscriptVersion(previous, PENDING_VERSION) !== setUserscriptVersion(draft, PENDING_VERSION);
  const version = changed
    ? nextUserscriptVersion(previousVersion, versionDatestamp(now))
    : previousVersion;

  fs.writeFileSync(targetPath, setUserscriptVersion(draft, version), 'utf8');
  return {version, changed};
}

module.exports = {
  runtimeDir,
  readRuntime,
  renderRuntime,
  VERSION_PLACEHOLDER,
  PENDING_VERSION,
  readUserscriptVersion,
  setUserscriptVersion,
  compareVersions,
  versionDatestamp,
  nextUserscriptVersion,
  writeVersionedUserscript
};
