// ==UserScript==
// @name        Zoopdog Nom Ruby
// @description Add Chu Nom ruby annotations to Vietnamese text using Zoopdog dictionary data
// @author      Zoopdog Contributors
// @namespace   https://github.com/tabidots/zoopdog
// @match       *://*/*
// @grant       GM_addStyle
// @version     __ZOOPDOG_VERSION__
// @updateURL   __ZOOPDOG_UPDATE_URL__
// @downloadURL __ZOOPDOG_DOWNLOAD_URL__
// ==/UserScript==

(function() {
  'use strict';

  // Generated by scripts/build-nom-userscript.js from zd-extension/db_src/vnedict2.json.
  // Also merges zd-extension/db_src/mdx_nom.json and user_nom_entries.jsonc when present.
  // Dictionary entries embedded: __ZOOPDOG_ENTRY_COUNT__
  var NOM_MAP = {"__ZOOPDOG_NOM_MAP__": true};

  var SETTINGS = {
    // "safe" annotates longer ASCII-only Vietnamese words while still skipping
    // short/common English words such as "an", "to", or "no".
    // Set to true to annotate every ASCII-only entry, or false to skip all of them.
    annotateAsciiTerms: 'safe',
    // False shows only the first known Chu Nom candidate as ruby; all candidates stay in title.
    showAllVariants: false,
    rescanIntervalMs: 500
  };

  var doc = document;
  var newNodes = [];
  var changedNodes = [];
  // A page that streams text rewrites its own text nodes in place. The nodes this script
  // inserted next to such a node still hold the previous text, so they are remembered here
  // and dropped before the rewritten node is annotated again.
  var injections = new WeakMap();
  var wordCharPattern = /[-0-9A-Za-zÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠƯàáâãèéêìíòóôõùúăđĩũơưẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀẾỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪỬỮỰỲỴÝỶỸạảấầẩẫậắằẳẵặẹẻẽềếểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ\u0300-\u036f]/u;
  var whitespacePattern = /\s/u;
  var nonAsciiPattern = /[^\x00-\x7F]/;
  var vietnameseSignalPattern = /[ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠƯàáâãèéêìíòóôõùúăđĩũơưẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀẾỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪỬỮỰỲỴÝỶỸạảấầẩẫậắằẳẵặẹẻẽềếểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ\u0300-\u036f]/u;
  var asciiBlocklist = {
    a: true,
    am: true,
    an: true,
    as: true,
    at: true,
    be: true,
    by: true,
    can: true,
    do: true,
    go: true,
    he: true,
    in: true,
    is: true,
    it: true,
    me: true,
    no: true,
    on: true,
    or: true,
    so: true,
    to: true,
    us: true,
    we: true
  };
  var trie = buildTrie(NOM_MAP);

  function buildTrie(map) {
    var root = {};

    Object.keys(map).forEach(function(term) {
      if (SETTINGS.annotateAsciiTerms === false && !nonAsciiPattern.test(term)) {
        return;
      }

      var node = root;
      for (var i = 0; i < term.length; i++) {
        var ch = term.charAt(i);
        node.children = node.children || {};
        node.children[ch] = node.children[ch] || {};
        node = node.children[ch];
      }
      node.value = map[term];
    });

    return root;
  }

  function isWordChar(ch) {
    return !!ch && wordCharPattern.test(ch);
  }

  function isWhitespace(ch) {
    return !!ch && whitespacePattern.test(ch);
  }

  function mutationHandler(mutationList) {
    mutationList.forEach(function(mutationRecord) {
      if (mutationRecord.type === 'characterData') {
        changedNodes.push(mutationRecord.target);
        return;
      }

      mutationRecord.addedNodes.forEach(function(node) {
        newNodes.push(node);
      });
    });
  }

  // Splitting a text node and rewriting its tail are character data changes of this
  // script's own making, so a node still holding the text left behind by the last pass has
  // nothing new to annotate.
  function refreshChangedNode(node) {
    var injection = injections.get(node);

    if (injection) {
      if (injection.text === node.nodeValue) {
        return;
      }

      injections.delete(node);
      injection.nodes.forEach(function(inserted) {
        if (inserted.parentNode) {
          inserted.parentNode.removeChild(inserted);
        }
      });
    }

    newNodes.push(node);
  }

  function scanTextNodes(node) {
    if (!node || !node.parentNode || !doc.body.contains(node)) {
      return;
    }

    var excludedTags = {
      ruby: true,
      rt: true,
      rp: true,
      script: true,
      style: true,
      noscript: true,
      select: true,
      textarea: true,
      input: true,
      button: true,
      option: true,
      code: true,
      pre: true,
      kbd: true,
      samp: true
    };

    switch (node.nodeType) {
    case Node.ELEMENT_NODE:
      if (node.tagName.toLowerCase() in excludedTags || node.isContentEditable) {
        return;
      }
      Array.from(node.childNodes).forEach(scanTextNodes);
      return;

    case Node.DOCUMENT_FRAGMENT_NODE:
      Array.from(node.childNodes).forEach(scanTextNodes);
      return;

    case Node.TEXT_NODE:
      annotateTextNode(node);
    }
  }

  function annotateTextNode(textNode) {
    var inserted = [];
    var node = textNode;
    var tail;

    while ((tail = addRuby(node))) {
      inserted.push(tail.previousSibling, tail);
      node = tail;
    }

    if (inserted.length) {
      injections.set(textNode, {nodes: inserted, text: textNode.nodeValue});
    }
  }

  function addRuby(textNode) {
    var text = textNode.nodeValue;
    var match = findNomMatch(text);

    if (!match) {
      return null;
    }

    var after = textNode.splitText(match.index);
    var matchedText = after.nodeValue.substring(0, match.length);
    after.nodeValue = after.nodeValue.substring(match.length);

    var ruby = doc.createElement('ruby');
    ruby.className = 'zoopdog-nom-ruby';
    ruby.title = 'Chu Nom: ' + match.nom;
    ruby.appendChild(doc.createTextNode(matchedText));

    var rt = doc.createElement('rt');
    rt.className = 'zoopdog-nom-rt';
    rt.textContent = SETTINGS.showAllVariants ? match.nom : match.nom.split(' / ')[0];
    ruby.appendChild(rt);

    after.parentNode.insertBefore(ruby, after);
    return after;
  }

  function findNomMatch(text) {
    for (var i = 0; i < text.length; i++) {
      if (!isWordChar(text.charAt(i)) || isWordChar(text.charAt(i - 1))) {
        continue;
      }

      var match = matchAt(text, i);
      if (match) {
        return match;
      }
    }

    return null;
  }

  function matchAt(text, start) {
    var node = trie;
    var i = start;
    var best = null;

    while (i < text.length) {
      var ch = text.charAt(i);

      if (isWhitespace(ch)) {
        if (!node.children || !node.children[' ']) {
          break;
        }

        while (i < text.length && isWhitespace(text.charAt(i))) {
          i++;
        }
        node = node.children[' '];
      } else {
        ch = ch.toLowerCase();
        if (!node.children || !node.children[ch]) {
          break;
        }

        node = node.children[ch];
        i++;
      }

      if (node.value && !isWordChar(text.charAt(i)) && shouldAnnotateMatch(text, start, i)) {
        best = {
          index: start,
          length: i - start,
          nom: node.value
        };
      }
    }

    return best;
  }

  function shouldAnnotateMatch(text, start, end) {
    var matchedText = text.substring(start, end);

    if (nonAsciiPattern.test(matchedText) || SETTINGS.annotateAsciiTerms === true) {
      return true;
    }

    if (SETTINGS.annotateAsciiTerms === false) {
      return false;
    }

    var normalized = matchedText.toLowerCase().replace(/\s+/g, ' ');
    var letterCount = normalized.replace(/\s/g, '').length;

    if (letterCount >= 3 && !asciiBlocklist[normalized]) {
      return true;
    }

    return hasVietnameseContext(text, start, end);
  }

  function hasVietnameseContext(text, start, end) {
    var contextStart = Math.max(0, start - 80);
    var contextEnd = Math.min(text.length, end + 80);
    return vietnameseSignalPattern.test(text.substring(contextStart, contextEnd));
  }

  function addStyle(css) {
    if (typeof GM_addStyle === 'function') {
      GM_addStyle(css);
      return;
    }

    var head = doc.getElementsByTagName('head')[0];
    if (!head) {
      return;
    }

    var style = doc.createElement('style');
    style.type = 'text/css';
    style.textContent = css;
    head.appendChild(style);
  }

  function main() {
    if (!doc.body) {
      window.setTimeout(main, 50);
      return;
    }

    addStyle([
      'ruby.zoopdog-nom-ruby { ruby-position: over; }',
      'ruby.zoopdog-nom-ruby > rt.zoopdog-nom-rt {',
      '  color: #B6638F;',
      '  font-size: 0.65em;',
      '  font-weight: 600;',
      '  line-height: 1;',
      '  user-select: none;',
      '}'
    ].join('\n'));

    newNodes.push(doc.body);

    var observer = new MutationObserver(mutationHandler);
    observer.observe(doc.body, {characterData: true, childList: true, subtree: true});

    function rescanTextNodes() {
      mutationHandler(observer.takeRecords());

      if (changedNodes.length) {
        var changed = changedNodes.slice();
        changedNodes.length = 0;
        changed.forEach(refreshChangedNode);
      }

      if (!newNodes.length) {
        return;
      }

      var nodes = newNodes.slice();
      newNodes.length = 0;
      nodes.forEach(scanTextNodes);
    }

    rescanTextNodes();
    window.setInterval(rescanTextNodes, SETTINGS.rescanIntervalMs);
  }

  if (typeof NodeList.prototype.forEach === 'undefined') {
    NodeList.prototype.forEach = function(callback, thisArg) {
      thisArg = thisArg || window;
      for (var i = 0; i < this.length; i++) {
        callback.call(thisArg, this[i], i, this);
      }
    };
  }

  main();
})();
