// ==UserScript==
// @name        Zoopdog Nom Ruby__ZOOPDOG_NAME_SUFFIX__
// @description Add Chu Nom ruby annotations to Vietnamese text using Zoopdog dictionary data
// @author      Zoopdog Contributors
// @namespace   https://github.com/tabidots/zoopdog
// @match       *://*/*
// @exclude     http://127.0.0.1:8770/*
// @exclude     http://localhost:8770/*
// @grant       GM_addStyle
// @version     __ZOOPDOG_VERSION__
// @updateURL   __ZOOPDOG_UPDATE_URL__
// @downloadURL __ZOOPDOG_DOWNLOAD_URL__
// ==/UserScript==

(function() {
  'use strict';

  // ===== zd-extension/js/zd-nom-match.js =====
  __ZOOPDOG_NOM_MATCH_ENGINE__

  // ===== zd-extension/js/zd-words.js =====
  __ZOOPDOG_WORDS__

  // Generated by scripts/build-nom-userscript.js from zd-extension/db_src/vnedict2.json.
  // Also merges zd-extension/db_src/mdx_nom.json and user_nom_entries.jsonc when present.
  // Dictionary entries embedded: __ZOOPDOG_ENTRY_COUNT__
  var NOM_MAP = {"__ZOOPDOG_NOM_MAP__": true};

  // Exact spelling -> its own display order, from user_nom_order.jsonc rows marked
  // `"caseSensitive": true` (e.g. the surname "Đỗ", read differently from the ordinary word
  // "đỗ"). See zd-nom-match.js's zdCreateNomMatcher for where this is checked.
  var CASE_SENSITIVE_NOM_MAP = {"__ZOOPDOG_CASE_SENSITIVE_NOM_MAP__": true};

  var SETTINGS = {
    // "safe" annotates longer ASCII-only Vietnamese words while still skipping
    // short/common English words such as "an", "to", or "no".
    // Set to true to annotate every ASCII-only entry, or false to skip all of them.
    annotateAsciiTerms: 'safe',
    // False shows only the first known Chu Nom candidate as ruby; all candidates stay in title.
    showAllVariants: false,
    rescanIntervalMs: 500
  };

  var doc = document;
  var newNodes = new Set();
  var changedNodes = new Set();
  // A page that streams text rewrites its own text nodes in place. The nodes this script
  // inserted next to such a node still hold the previous text, so they are remembered here
  // and dropped before the rewritten node is annotated again.
  var injections = new WeakMap();
  var nomMatcher = zdCreateNomMatcher(NOM_MAP, SETTINGS, CASE_SENSITIVE_NOM_MAP);
  // A video-caption or translation-overlay widget (Eudict/欧路翻译, Immersive Translate) renders
  // its actual on-screen text inside its own *open* shadow root, to keep the host page's CSS
  // from leaking in. That content is real, painted DOM, but it is not part of any element's
  // childNodes and a MutationObserver rooted at document.body never sees mutations inside it --
  // both the initial scan and the observer have to be told about each shadow root separately.
  // Declared here (not inside main()) so scanTextNodes and the attachShadow patch below can
  // both reach the same observer instance.
  var observer;
  var observedShadowRoots = new WeakSet();
  var rubyCss = [
    '@font-face {',
    "  font-family: 'Zoopdog Nom Na Tong';",
    "  src: __ZOOPDOG_NOM_FONT_SRC__;",
    '  font-display: swap;',
    '}',
    'ruby.zoopdog-nom-ruby { ruby-position: over; }',
    'ruby.zoopdog-nom-ruby > rt.zoopdog-nom-rt {',
    '  color: #B6638F;',
    "  font-family: 'Zoopdog Nom Na Tong', sans-serif;",
    '  font-size: 0.65em;',
    '  font-weight: 600;',
    '  line-height: 1;',
    '  user-select: none;',
    '}'
  ].join('\n');

  // Eudict's caption overlay caps each language row at a few lines' height (`max-height: 3.6em`,
  // `overflow: hidden`). A ruby line is taller than a plain one, so an annotated row no longer
  // fits: its lower lines are clipped, and because the row centres its content the overflow
  // spills upward over the row above. Only the overlay's own rows are lifted, and only inside
  // shadow roots -- the overlay's box is anchored at the bottom, so it simply grows upward.
  var captionCss = [
    '.eudic-chrome-extension-video-src,',
    '.eudic-chrome-extension-video-dest {',
    '  max-height: none !important;',
    '  overflow: visible !important;',
    '}'
  ].join('\n');

  function mutationHandler(mutationList) {
    mutationList.forEach(function(mutationRecord) {
      if (mutationRecord.type === 'characterData') {
        changedNodes.add(mutationRecord.target);
        return;
      }

      // Reconcile the connected container, not only the reported additions. Mobile
      // translation widgets can assemble their first line outside the observed subtree and
      // attach it before streaming later lines. Scanning the child-list target lets that
      // next mutation recover the already-present first line as well.
      newNodes.add(mutationRecord.target);
    });
  }

  // Splitting a text node and rewriting its tail are character data changes of this
  // script's own making, so a node still holding the text left behind by the last pass has
  // nothing new to annotate.
  function refreshChangedNode(node) {
    var injection = injections.get(node);

    if (injection) {
      if (injection.text === node.nodeValue) {
        return;
      }

      injections.delete(node);
      injection.nodes.forEach(function(inserted) {
        if (inserted.parentNode) {
          inserted.parentNode.removeChild(inserted);
        }
      });
    }

    newNodes.add(node);
  }

  var EXCLUDED_TAGS = {
    ruby: true,
    rt: true,
    rp: true,
    script: true,
    style: true,
    noscript: true,
    select: true,
    textarea: true,
    input: true,
    button: true,
    option: true,
    code: true,
    pre: true,
    kbd: true,
    samp: true
  };

  function isExcludedElement(element) {
    return element.tagName.toLowerCase() in EXCLUDED_TAGS || element.isContentEditable;
  }

  function scanTextNodes(node) {
    // `isConnected` is true for a node reachable from the document either directly or through
    // an attached shadow tree, unlike `doc.body.contains(node)` -- which a ShadowRoot always
    // fails, since a shadow tree is a separate root, not a descendant in the light-DOM sense.
    if (!node || !node.isConnected) {
      return;
    }

    switch (node.nodeType) {
    case Node.ELEMENT_NODE:
      if (isExcludedElement(node)) {
        return;
      }
      Array.from(node.childNodes).forEach(scanTextNodes);
      if (node.shadowRoot) {
        watchShadowRoot(node.shadowRoot);
      }
      return;

    case Node.DOCUMENT_FRAGMENT_NODE:
      Array.from(node.childNodes).forEach(scanTextNodes);
      return;

    case Node.TEXT_NODE:
      annotateTextNode(node);
    }
  }

  // A ShadowRoot is itself a DocumentFragment, so scanTextNodes already knows how to walk its
  // childNodes once handed one -- what it does not get for free is future observation, which
  // needs its own explicit observe() call per shadow root (see the comment on `observer` above).
  function watchShadowRoot(root) {
    if (observedShadowRoots.has(root)) {
      return;
    }
    observedShadowRoots.add(root);
    addStyleToRoot(root, rubyCss + '\n' + captionCss);
    if (observer) {
      observer.observe(root, {characterData: true, childList: true, subtree: true});
    }
    scanTextNodes(root);
  }

  // Catches a shadow root the moment it is created, for the host element this script has not
  // walked past yet (a widget that attaches its shadow root only once the video/track it
  // depends on is ready, well after this script's own initial scan). `watchShadowRoot` above
  // handles a shadow root that already existed when its host was scanned; this handles one that
  // does not exist yet. Every open shadow root gets watched, from any script or extension on
  // the page -- not only known caption widgets -- since there is no reliable way to tell in
  // advance which ones will carry annotatable text.
  function patchAttachShadow() {
    if (typeof Element === 'undefined' || !Element.prototype.attachShadow) {
      return;
    }
    var original = Element.prototype.attachShadow;
    Element.prototype.attachShadow = function(init) {
      var root = original.call(this, init);
      if (root.mode === 'open') {
        watchShadowRoot(root);
      }
      return root;
    };
  }

  var AHEAD_MAX_CHARS = 400;
  var AHEAD_MAX_NODES = 60;

  // True when `node` sits inside markup this script never annotates (an existing <ruby>, code,
  // an input, ...), up to and including `boundary`.
  function isInsideExcluded(node, boundary) {
    for (var el = node.parentNode; el; el = el.parentNode) {
      if (el.nodeType === Node.ELEMENT_NODE && isExcludedElement(el)) {
        return true;
      }
      if (el === boundary) {
        return false;
      }
    }
    return false;
  }

  // A caption widget (Eudict) renders every word in its own wrapper, so a dictionary entry of
  // several words never sits inside one text node and matching a node by itself can only ever
  // see one word of it. This returns the node's text followed by the word/space run that
  // continues in the text nodes after it -- the same reading order zd-words.js gives the popup
  // dictionary -- together with which node each stretch of that text came from. Only the first
  // node is ever annotated *from*; the rest is context, and the words of a match found in it
  // are wrapped where they are (see annotateAcrossNodes).
  function readAhead(textNode, own) {
    var text = own.replace(/\u00a0/g, ' ');
    var ahead = {text: text, segments: [{node: textNode, start: 0, end: own.length}]};

    if (!nomMatcher.canContinuePast(text) || !textNode.parentNode) {
      return ahead;
    }

    var boundary = zdContainerBoundary(textNode);
    var node = zdNextTextNode(textNode, boundary);
    var guard = 0;

    while (node && text.length < AHEAD_MAX_CHARS && guard < AHEAD_MAX_NODES) {
      guard++;
      var data = node.nodeValue;
      if (isInsideExcluded(node, boundary) || data !== data.normalize('NFC')) {
        break;
      }

      var i = 0;
      while (i < data.length && (zdIsWordChar(data.charAt(i)) || /\s/.test(data.charAt(i)))) {
        i++;
      }
      if (i === 0) {
        break;
      }

      // "ch" + "ỉ" in two nodes is one word split by markup, not two words: reading on would
      // treat the first half as a whole word, so stop before it if it began after the node.
      if (zdIsWordChar(text.charAt(text.length - 1)) && zdIsWordChar(data.charAt(0))) {
        var cut = text.length;
        while (cut > 0 && zdIsWordChar(text.charAt(cut - 1))) {
          cut--;
        }
        if (cut >= own.length) {
          text = text.substring(0, cut);
          ahead.segments = ahead.segments.filter(function(segment) {
            return segment.start < cut;
          });
          ahead.segments.forEach(function(segment) {
            segment.end = Math.min(segment.end, cut);
          });
        } else {
          return {text: text.substring(0, own.length), segments: [ahead.segments[0]]};
        }
        break;
      }

      ahead.segments.push({node: node, start: text.length, end: text.length + i});
      text += data.substring(0, i).replace(/\u00a0/g, ' ');
      if (i < data.length) {
        break;
      }
      node = zdNextTextNode(node, boundary);
    }

    ahead.text = text;
    return ahead;
  }

  function annotateTextNode(textNode) {
    // Some pages and extensions rewrite text nodes into decomposed Unicode, where "vùng" is
    // "v" + "u" + U+0300 + "ng" and stops the precomposed-keyed trie one combining mark deep.
    // Normalising in place keeps splitText offsets valid against the string being matched.
    var normalized = textNode.nodeValue.normalize('NFC');

    if (normalized !== textNode.nodeValue) {
      textNode.nodeValue = normalized;
    }

    // Matching walks the original, un-split text so a short ASCII-only word (e.g. "xe")
    // keeps the Vietnamese diacritics around it in view for shouldAnnotateMatch, even after
    // an earlier match in the same sentence has been spliced out into its own ruby node.
    var ownText = textNode.nodeValue;
    var ahead = readAhead(textNode, ownText);
    var inserted = [];
    var node = textNode;
    var offset = 0;
    var match;

    // A match is this node's to annotate only if it starts inside it; one that starts in the
    // text read ahead belongs to the node it starts in.
    while ((match = nomMatcher.findNomMatch(ahead.text, offset)) && match.index < ownText.length) {
      if (match.index + match.length > ownText.length) {
        annotateAcrossNodes(match, ahead, node, offset, inserted);
        break;
      }

      var tail = wrapPiece(node, match.index - offset, match.index - offset + match.length,
        rubyText(match.nom), match.nom);
      inserted.push(tail.previousSibling, tail);
      node = tail;
      offset = match.index + match.length;
    }

    if (inserted.length) {
      injections.set(textNode, {nodes: inserted, text: textNode.nodeValue});
    }
  }

  function rubyText(nom) {
    return SETTINGS.showAllVariants ? nom : nom.split(' / ')[0];
  }

  // Splits `node` around [start, end), moves that text into a <ruby> carrying `reading`, and
  // returns the node holding whatever followed it.
  function wrapPiece(node, start, end, reading, nom) {
    var after = node.splitText(start);
    var matchedText = after.nodeValue.substring(0, end - start);
    after.nodeValue = after.nodeValue.substring(end - start);

    var ruby = doc.createElement('ruby');
    ruby.className = 'zoopdog-nom-ruby';
    ruby.title = 'Chu Nom: ' + nom;
    ruby.appendChild(doc.createTextNode(matchedText));

    var rt = doc.createElement('rt');
    rt.className = 'zoopdog-nom-rt';
    rt.textContent = reading;
    ruby.appendChild(rt);

    after.parentNode.insertBefore(ruby, after);
    return after;
  }

  // The word spans (start/end offsets into `text`) inside [from, to).
  function wordSpans(text, from, to) {
    var spans = [];
    var i = from;
    while (i < to) {
      if (!zdNomIsWordChar(text.charAt(i))) {
        i++;
        continue;
      }
      var start = i;
      while (i < to && zdNomIsWordChar(text.charAt(i))) {
        i++;
      }
      spans.push({start: start, end: i});
    }
    return spans;
  }

  // A match whose words sit in different text nodes cannot share one <ruby> -- a <ruby> holds
  // one node's text -- so each word is wrapped in place and given one character of the entry's
  // reading. That needs the reading to have as many characters as the entry has words, as
  // "chỉ trích" -> 指責 does; a reading of any other shape goes on the first word whole.
  // `node`/`offset` are this node's not-yet-consumed tail and where that tail starts.
  function annotateAcrossNodes(match, ahead, node, offset, inserted) {
    var spans = wordSpans(ahead.text, match.index, match.index + match.length);
    var reading = match.nom.split(' / ')[0];
    var chars = Array.from(reading);
    var perWord = chars.length === spans.length;
    var pieces = [];

    for (var k = 0; k < spans.length; k++) {
      var span = spans[k];
      var segment = ahead.segments.filter(function(candidate) {
        return span.start >= candidate.start && span.end <= candidate.end;
      })[0];
      if (!segment) {
        return;
      }
      pieces.push({
        segment: segment,
        start: span.start - segment.start,
        end: span.end - segment.start,
        reading: perWord ? chars[k] : (k === 0 ? reading : null)
      });
    }

    // Each segment's remaining tail and where that tail starts in the segment's own text: the
    // first segment is this node, already partly consumed by matches before this one.
    var tails = new Map();
    tails.set(ahead.segments[0], {node: node, base: offset});

    pieces.forEach(function(piece) {
      var isOwn = piece.segment === ahead.segments[0];
      var tail = tails.get(piece.segment) || {node: piece.segment.node, base: 0};

      if (piece.reading === null) {
        return;
      }

      var after = wrapPiece(tail.node, piece.start - tail.base, piece.end - tail.base,
        piece.reading, match.nom);
      tails.set(piece.segment, {node: after, base: piece.end});
      if (isOwn) {
        inserted.push(after.previousSibling, after);
      }
    });
  }

  function addStyle(css) {
    if (typeof GM_addStyle === 'function') {
      GM_addStyle(css);
      return;
    }

    var head = doc.getElementsByTagName('head')[0];
    if (!head) {
      return;
    }

    var style = doc.createElement('style');
    style.type = 'text/css';
    style.textContent = css;
    head.appendChild(style);
  }

  // Shadow DOM's whole point is that a page's own <style> (however it got there, GM_addStyle
  // included) does not reach inside it -- so the ruby/rt rules that make an annotation visible
  // have to be appended a second time, directly into each shadow root this script watches, or
  // the annotation renders with no font/color/positioning at all despite being present in the
  // DOM (correct markup, invisible paint -- see docs/build.md).
  function addStyleToRoot(root, css) {
    var style = doc.createElement('style');
    style.textContent = css;
    root.appendChild(style);
  }

  function main() {
    if (!doc.body) {
      window.setTimeout(main, 50);
      return;
    }

    // The font src in rubyCss is a github raw-styled URL in the committed build (small file,
    // but blocked by font-src CSP on sites like YouTube -- document.fonts then reports this
    // family as "error" and every rare Nom glyph silently falls back to invisible tofu in
    // sans-serif) and a `data:` URI embedding the whole font in the -local build (large file,
    // but immune to font-src since there is no network fetch to block). See docs/build.md.
    addStyle(rubyCss);

    newNodes.add(doc.body);

    patchAttachShadow();

    var frameScheduled = false;

    // A caption widget replaces its whole line for every cue. Waiting for the interval tick
    // paints the plain line first and swaps in the ruby up to rescanIntervalMs later, which
    // shows as flicker. A frame callback runs before the next paint, so the line is annotated
    // before it is ever shown; the interval stays as the fallback (hidden tabs pause frames).
    function scheduleFrameScan() {
      if (frameScheduled || typeof window.requestAnimationFrame !== 'function') {
        return;
      }
      frameScheduled = true;
      window.requestAnimationFrame(function() {
        frameScheduled = false;
        rescanTextNodes();
      });
    }

    observer = new MutationObserver(function(mutationList) {
      mutationHandler(mutationList);
      scheduleFrameScan();
    });
    observer.observe(doc.body, {characterData: true, childList: true, subtree: true});

    function rescanTextNodes() {
      mutationHandler(observer.takeRecords());

      if (changedNodes.size) {
        var changed = Array.from(changedNodes);
        changedNodes.clear();
        changed.forEach(refreshChangedNode);
      }

      if (!newNodes.size) {
        return;
      }

      var nodes = Array.from(newNodes);
      newNodes.clear();
      nodes.forEach(scanTextNodes);
    }

    rescanTextNodes();
    window.setInterval(rescanTextNodes, SETTINGS.rescanIntervalMs);
  }

  if (typeof NodeList.prototype.forEach === 'undefined') {
    NodeList.prototype.forEach = function(callback, thisArg) {
      thisArg = thisArg || window;
      for (var i = 0; i < this.length; i++) {
        callback.call(thisArg, this[i], i, this);
      }
    };
  }

  main();
})();
