// ==UserScript==
// @name        Zoopdog Nom Ruby__ZOOPDOG_NAME_SUFFIX__
// @description Add Chu Nom ruby annotations to Vietnamese text using Zoopdog dictionary data
// @author      Zoopdog Contributors
// @namespace   https://github.com/tabidots/zoopdog
// @match       *://*/*
// @exclude     http://127.0.0.1:8770/*
// @exclude     http://localhost:8770/*
// @grant       GM_addStyle
// @version     __ZOOPDOG_VERSION__
// @updateURL   __ZOOPDOG_UPDATE_URL__
// @downloadURL __ZOOPDOG_DOWNLOAD_URL__
// ==/UserScript==

(function() {
  'use strict';

  // ===== zd-extension/js/zd-nom-match.js =====
  __ZOOPDOG_NOM_MATCH_ENGINE__

  // Generated by scripts/build-nom-userscript.js from zd-extension/db_src/vnedict2.json.
  // Also merges zd-extension/db_src/mdx_nom.json and user_nom_entries.jsonc when present.
  // Dictionary entries embedded: __ZOOPDOG_ENTRY_COUNT__
  var NOM_MAP = {"__ZOOPDOG_NOM_MAP__": true};

  var SETTINGS = {
    // "safe" annotates longer ASCII-only Vietnamese words while still skipping
    // short/common English words such as "an", "to", or "no".
    // Set to true to annotate every ASCII-only entry, or false to skip all of them.
    annotateAsciiTerms: 'safe',
    // False shows only the first known Chu Nom candidate as ruby; all candidates stay in title.
    showAllVariants: false,
    rescanIntervalMs: 500
  };

  var doc = document;
  var newNodes = new Set();
  var changedNodes = new Set();
  // A page that streams text rewrites its own text nodes in place. The nodes this script
  // inserted next to such a node still hold the previous text, so they are remembered here
  // and dropped before the rewritten node is annotated again.
  var injections = new WeakMap();
  var nomMatcher = zdCreateNomMatcher(NOM_MAP, SETTINGS);
  // A video-caption or translation-overlay widget (Eudict/欧路翻译, Immersive Translate) renders
  // its actual on-screen text inside its own *open* shadow root, to keep the host page's CSS
  // from leaking in. That content is real, painted DOM, but it is not part of any element's
  // childNodes and a MutationObserver rooted at document.body never sees mutations inside it --
  // both the initial scan and the observer have to be told about each shadow root separately.
  // Declared here (not inside main()) so scanTextNodes and the attachShadow patch below can
  // both reach the same observer instance.
  var observer;
  var observedShadowRoots = new WeakSet();
  var rubyCss = [
    '@font-face {',
    "  font-family: 'Zoopdog Nom Na Tong';",
    "  src: __ZOOPDOG_NOM_FONT_SRC__;",
    '  font-display: swap;',
    '}',
    'ruby.zoopdog-nom-ruby { ruby-position: over; }',
    'ruby.zoopdog-nom-ruby > rt.zoopdog-nom-rt {',
    '  color: #B6638F;',
    "  font-family: 'Zoopdog Nom Na Tong', sans-serif;",
    '  font-size: 0.65em;',
    '  font-weight: 600;',
    '  line-height: 1;',
    '  user-select: none;',
    '}'
  ].join('\n');

  function mutationHandler(mutationList) {
    mutationList.forEach(function(mutationRecord) {
      if (mutationRecord.type === 'characterData') {
        changedNodes.add(mutationRecord.target);
        return;
      }

      // Reconcile the connected container, not only the reported additions. Mobile
      // translation widgets can assemble their first line outside the observed subtree and
      // attach it before streaming later lines. Scanning the child-list target lets that
      // next mutation recover the already-present first line as well.
      newNodes.add(mutationRecord.target);
    });
  }

  // Splitting a text node and rewriting its tail are character data changes of this
  // script's own making, so a node still holding the text left behind by the last pass has
  // nothing new to annotate.
  function refreshChangedNode(node) {
    var injection = injections.get(node);

    if (injection) {
      if (injection.text === node.nodeValue) {
        return;
      }

      injections.delete(node);
      injection.nodes.forEach(function(inserted) {
        if (inserted.parentNode) {
          inserted.parentNode.removeChild(inserted);
        }
      });
    }

    newNodes.add(node);
  }

  function scanTextNodes(node) {
    // `isConnected` is true for a node reachable from the document either directly or through
    // an attached shadow tree, unlike `doc.body.contains(node)` -- which a ShadowRoot always
    // fails, since a shadow tree is a separate root, not a descendant in the light-DOM sense.
    if (!node || !node.isConnected) {
      return;
    }

    var excludedTags = {
      ruby: true,
      rt: true,
      rp: true,
      script: true,
      style: true,
      noscript: true,
      select: true,
      textarea: true,
      input: true,
      button: true,
      option: true,
      code: true,
      pre: true,
      kbd: true,
      samp: true
    };

    switch (node.nodeType) {
    case Node.ELEMENT_NODE:
      if (node.tagName.toLowerCase() in excludedTags || node.isContentEditable) {
        return;
      }
      Array.from(node.childNodes).forEach(scanTextNodes);
      if (node.shadowRoot) {
        watchShadowRoot(node.shadowRoot);
      }
      return;

    case Node.DOCUMENT_FRAGMENT_NODE:
      Array.from(node.childNodes).forEach(scanTextNodes);
      return;

    case Node.TEXT_NODE:
      annotateTextNode(node);
    }
  }

  // A ShadowRoot is itself a DocumentFragment, so scanTextNodes already knows how to walk its
  // childNodes once handed one -- what it does not get for free is future observation, which
  // needs its own explicit observe() call per shadow root (see the comment on `observer` above).
  function watchShadowRoot(root) {
    if (observedShadowRoots.has(root)) {
      return;
    }
    observedShadowRoots.add(root);
    addStyleToRoot(root, rubyCss);
    if (observer) {
      observer.observe(root, {characterData: true, childList: true, subtree: true});
    }
    scanTextNodes(root);
  }

  // Catches a shadow root the moment it is created, for the host element this script has not
  // walked past yet (a widget that attaches its shadow root only once the video/track it
  // depends on is ready, well after this script's own initial scan). `watchShadowRoot` above
  // handles a shadow root that already existed when its host was scanned; this handles one that
  // does not exist yet. Every open shadow root gets watched, from any script or extension on
  // the page -- not only known caption widgets -- since there is no reliable way to tell in
  // advance which ones will carry annotatable text.
  function patchAttachShadow() {
    if (typeof Element === 'undefined' || !Element.prototype.attachShadow) {
      return;
    }
    var original = Element.prototype.attachShadow;
    Element.prototype.attachShadow = function(init) {
      var root = original.call(this, init);
      if (root.mode === 'open') {
        watchShadowRoot(root);
      }
      return root;
    };
  }

  function annotateTextNode(textNode) {
    // Some pages and extensions rewrite text nodes into decomposed Unicode, where "vùng" is
    // "v" + "u" + U+0300 + "ng" and stops the precomposed-keyed trie one combining mark deep.
    // Normalising in place keeps splitText offsets valid against the string being matched.
    var normalized = textNode.nodeValue.normalize('NFC');

    if (normalized !== textNode.nodeValue) {
      textNode.nodeValue = normalized;
    }

    // Matching walks the original, un-split text so a short ASCII-only word (e.g. "xe")
    // keeps the Vietnamese diacritics around it in view for shouldAnnotateMatch, even after
    // an earlier match in the same sentence has been spliced out into its own ruby node.
    var fullText = textNode.nodeValue;
    var inserted = [];
    var node = textNode;
    var offset = 0;
    var tail;

    while ((tail = addRuby(node, fullText, offset))) {
      inserted.push(tail.node.previousSibling, tail.node);
      node = tail.node;
      offset = tail.offset;
    }

    if (inserted.length) {
      injections.set(textNode, {nodes: inserted, text: textNode.nodeValue});
    }
  }

  function addRuby(textNode, fullText, offset) {
    var match = nomMatcher.findNomMatch(fullText, offset);

    if (!match) {
      return null;
    }

    var after = textNode.splitText(match.index - offset);
    var matchedText = after.nodeValue.substring(0, match.length);
    after.nodeValue = after.nodeValue.substring(match.length);

    var ruby = doc.createElement('ruby');
    ruby.className = 'zoopdog-nom-ruby';
    ruby.title = 'Chu Nom: ' + match.nom;
    ruby.appendChild(doc.createTextNode(matchedText));

    var rt = doc.createElement('rt');
    rt.className = 'zoopdog-nom-rt';
    rt.textContent = SETTINGS.showAllVariants ? match.nom : match.nom.split(' / ')[0];
    ruby.appendChild(rt);

    after.parentNode.insertBefore(ruby, after);
    return {node: after, offset: match.index + match.length};
  }

  function addStyle(css) {
    if (typeof GM_addStyle === 'function') {
      GM_addStyle(css);
      return;
    }

    var head = doc.getElementsByTagName('head')[0];
    if (!head) {
      return;
    }

    var style = doc.createElement('style');
    style.type = 'text/css';
    style.textContent = css;
    head.appendChild(style);
  }

  // Shadow DOM's whole point is that a page's own <style> (however it got there, GM_addStyle
  // included) does not reach inside it -- so the ruby/rt rules that make an annotation visible
  // have to be appended a second time, directly into each shadow root this script watches, or
  // the annotation renders with no font/color/positioning at all despite being present in the
  // DOM (correct markup, invisible paint -- see docs/build.md).
  function addStyleToRoot(root, css) {
    var style = doc.createElement('style');
    style.textContent = css;
    root.appendChild(style);
  }

  function main() {
    if (!doc.body) {
      window.setTimeout(main, 50);
      return;
    }

    // The font src in rubyCss is a github raw-styled URL in the committed build (small file,
    // but blocked by font-src CSP on sites like YouTube -- document.fonts then reports this
    // family as "error" and every rare Nom glyph silently falls back to invisible tofu in
    // sans-serif) and a `data:` URI embedding the whole font in the -local build (large file,
    // but immune to font-src since there is no network fetch to block). See docs/build.md.
    addStyle(rubyCss);

    newNodes.add(doc.body);

    observer = new MutationObserver(mutationHandler);
    observer.observe(doc.body, {characterData: true, childList: true, subtree: true});
    patchAttachShadow();

    function rescanTextNodes() {
      mutationHandler(observer.takeRecords());

      if (changedNodes.size) {
        var changed = Array.from(changedNodes);
        changedNodes.clear();
        changed.forEach(refreshChangedNode);
      }

      if (!newNodes.size) {
        return;
      }

      var nodes = Array.from(newNodes);
      newNodes.clear();
      nodes.forEach(scanTextNodes);
    }

    rescanTextNodes();
    window.setInterval(rescanTextNodes, SETTINGS.rescanIntervalMs);
  }

  if (typeof NodeList.prototype.forEach === 'undefined') {
    NodeList.prototype.forEach = function(callback, thisArg) {
      thisArg = thisArg || window;
      for (var i = 0; i < this.length; i++) {
        callback.call(thisArg, this[i], i, this);
      }
    };
  }

  main();
})();
