// ==UserScript==
// @name        Zoopdog Popup Dictionary
// @description Vietnamese-English popup dictionary with Zoopdog pronunciation guide
// @author      Zoopdog Contributors
// @namespace   https://github.com/tabidots/zoopdog
// @match       *://*/*
// @grant       GM_addStyle
// @grant       GM_xmlhttpRequest
// @connect     127.0.0.1
// @connect     localhost
// @run-at      document-idle
// @version     __ZOOPDOG_VERSION__
// @updateURL   __ZOOPDOG_UPDATE_URL__
// @downloadURL __ZOOPDOG_DOWNLOAD_URL__
// ==/UserScript==

(function() {
__ZOOPDOG_RUNTIME_SOURCES__

  // Generated by scripts/build-popupdict-userscript.js from zd-extension/db_src/vnedict2.json.
  // Also merges zd-extension/db_src/user_nom_entries.jsonc when present.
  // Dictionary keys embedded: __ZOOPDOG_KEY_COUNT__
  var ZOO_DICTIONARY = {"__ZOOPDOG_DICTIONARY__": true};
  var ZOO_MAX_WORDS = __ZOOPDOG_MAX_WORDS__;

  var ZOO_SETTINGS = {
    dialect: 'hanoi',
    cjkDefinitionLineLength: 18,
    oldWordResetMs: 500
  };

  var ZOO_CJK_RE = /[\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF\u{20000}-\u{323AF}]/u;
  var ZOO_CJK_SEQUENCE_RE = /[\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF\u{20000}-\u{323AF}]+/gu;

  // ---------------------------------------------------------------------
  // Local mode
  //
  // Talks to the book-translator reader server (scripts/reader/tts_server.py
  // in the book-translator repo) running on the user's own machine, so
  // "Add Ch\u1EEF N\u00F4m entry" / "Set Ch\u1EEF N\u00F4m order" write to the very same
  // user_nom_entries.jsonc / user_nom_order.jsonc the reader itself edits.
  // Every piece below mirrors the reader's own modals (reader_nom.js,
  // reader_nom_order.js, and the shared shared/entry_forms.js,
  // shared/suggest.js, shared/modal.js, reader_entry_diff.js) field for
  // field -- same suggestion lookups, same notes re-translate, same
  // preview -> confirm diff -- just re-hosted against GM_xmlhttpRequest
  // instead of same-origin fetch, since this popup runs on arbitrary
  // third-party pages. `book` is never sent: both endpoints already treat a
  // missing book as "the shared dictionary", which is the only thing that
  // makes sense from a page that isn't the reader.
  // ---------------------------------------------------------------------

  var ZOO_LOCAL_BASE = 'http://127.0.0.1:8770';
  var ZOO_LOCAL_AVAILABLE = false;

  function zooHttpRequest(method, path, params) {
    return new Promise(function(resolve, reject) {
      if (typeof GM_xmlhttpRequest !== 'function') {
        reject(new Error('GM_xmlhttpRequest unavailable'));
        return;
      }
      var pairs = [];
      if (params) {
        Object.keys(params).forEach(function(key) {
          var value = params[key];
          if (value === undefined || value === null || value === '') return;
          pairs.push(encodeURIComponent(key) + '=' + encodeURIComponent(value));
        });
      }
      var query = pairs.join('&');
      var url = ZOO_LOCAL_BASE + path + (query ? (path.indexOf('?') === -1 ? '?' : '&') + query : '');
      GM_xmlhttpRequest({
        method: method,
        url: url,
        timeout: 8000,
        onload: function(response) {
          var payload = {};
          try {
            payload = JSON.parse(response.responseText || '{}');
          } catch (parseError) {
            payload = {};
          }
          if (response.status >= 200 && response.status < 300) {
            resolve(payload);
          } else {
            reject(new Error(payload.error || ('request failed (' + response.status + ')')));
          }
        },
        onerror: function() { reject(new Error('request failed')); },
        ontimeout: function() { reject(new Error('request timed out')); }
      });
    });
  }

  function zooGetJSON(path, params) { return zooHttpRequest('GET', path, params); }
  function zooPost(path, params) { return zooHttpRequest('POST', path, params); }

  function zooProbeLocalMode() {
    zooGetJSON('/healthz', null).then(function() {
      ZOO_LOCAL_AVAILABLE = true;
    }).catch(function() {
      ZOO_LOCAL_AVAILABLE = false;
    });
  }

  // -- suggestion / debounce / edit-tracking plumbing (mirrors shared/suggest.js) --

  function zooDebounce(fn, wait) {
    var timer = null;
    return function() {
      var args = arguments;
      clearTimeout(timer);
      timer = setTimeout(function() { fn.apply(null, args); }, wait);
    };
  }

  function zooCreateRaceGuard() {
    var latest = 0;
    return {
      begin: function() {
        var token = ++latest;
        return function() { return token === latest; };
      }
    };
  }

  function zooFetchSuggestions(kind, text) {
    if (!text) return Promise.resolve([]);
    return zooGetJSON('/v1/suggest', { kind: kind, text: text }).then(function(data) {
      return data.candidates || [];
    }).catch(function() { return []; });
  }

  function zooFetchNotesRefresh(kind, text, engineIndex) {
    if (!text) return Promise.resolve({ candidates: [], engine: '' });
    var params = { kind: kind, text: text, refresh: '1' };
    if (typeof engineIndex === 'number' && isFinite(engineIndex)) params.engine = String(engineIndex);
    return zooGetJSON('/v1/suggest', params).then(function(data) {
      return { candidates: data.candidates || [], engine: data.engine || '' };
    }).catch(function() { return { candidates: [], engine: '' }; });
  }

  function zooNotesEngineMessage(engine, ok) {
    if (!engine) return ok ? 'Re-translated.' : 'Re-translate failed -- try again in a moment.';
    return ok
      ? 'Re-translated with ' + engine + '.'
      : engine + ': no answer -- click again to try the next engine.';
  }

  function zooCreateEngineRotator() {
    var index = 0;
    return function() { return index++; };
  }

  function zooTrackEdits(input) {
    var edited = false;
    input.addEventListener('input', function() { edited = true; });
    return {
      get edited() { return edited; },
      isEdited: function() { return edited; },
      reset: function() { edited = false; },
      mark: function() { edited = true; }
    };
  }

  function zooFillDatalist(id, candidates) {
    var datalist = document.getElementById(id);
    if (!datalist) return;
    datalist.textContent = '';
    (candidates || []).forEach(function(value) {
      var option = document.createElement('option');
      option.value = value;
      datalist.appendChild(option);
    });
  }

  function zooSetAutofillDefault(input, value) {
    input.value = value;
    input.dataset.autofillDefault = value;
  }

  function zooWireDatalistAutoClear(input, isEdited) {
    input.addEventListener('focus', function() {
      if (!isEdited() && input.value && input.value === input.dataset.autofillDefault) input.value = '';
    });
    input.addEventListener('blur', function() {
      if (!isEdited() && !input.value && input.dataset.autofillDefault) input.value = input.dataset.autofillDefault;
    });
  }

  function zooWirePickerAutoClear(input) {
    var valueBeforeFocus = '';
    input.addEventListener('focus', function() {
      valueBeforeFocus = input.value;
      if (input.value) input.value = '';
    });
    input.addEventListener('blur', function() {
      if (!input.value) input.value = valueBeforeFocus;
    });
  }

  function zooTrimSelectionPunctuation(value) {
    return String(value || '').trim().replace(/^\p{P}+|\p{P}+$/gu, '').trim();
  }

  // -- entry-diff preview (mirrors reader_entry_diff.js) --

  var ZOO_ENTRY_DIFF_FIELD_LABELS = { nom: 'Ch\u1EEF N\u00F4m', explain: 'Note' };

  function zooEntryDiffFieldLabel(field) {
    var key = String(field || '');
    return ZOO_ENTRY_DIFF_FIELD_LABELS[key] || key.toUpperCase();
  }

  function zooEntryDiffSplit(from, to) {
    var before = Array.from(String(from || ''));
    var after = Array.from(String(to || ''));
    var head = 0;
    while (head < before.length && head < after.length && before[head] === after[head]) head += 1;
    var tail = 0;
    while (
      tail < before.length - head &&
      tail < after.length - head &&
      before[before.length - 1 - tail] === after[after.length - 1 - tail]
    ) {
      tail += 1;
    }
    return {
      head: before.slice(0, head).join(''),
      tail: tail ? before.slice(before.length - tail).join('') : '',
      fromMiddle: before.slice(head, before.length - tail).join(''),
      toMiddle: after.slice(head, after.length - tail).join('')
    };
  }

  function zooEntryDiffLineHtml(kind, mark, text, split, side) {
    var tag = kind === 'old' ? 'del' : 'ins';
    var inner;
    if (!text) {
      inner = '<span class="zd-entry-diff-empty">(empty)</span>';
    } else if (split && (split.head || split.tail)) {
      var middle = side === 'old' ? split.fromMiddle : split.toMiddle;
      inner = escapeHtml(split.head) + (middle ? '<mark>' + escapeHtml(middle) + '</mark>' : '') + escapeHtml(split.tail);
    } else {
      inner = escapeHtml(text);
    }
    return '<div class="zd-entry-diff-line zd-entry-diff-' + kind + '">' +
      '<span class="zd-entry-diff-mark" aria-hidden="true">' + mark + '</span>' +
      '<' + tag + '>' + inner + '</' + tag + '>' +
      '</div>';
  }

  function zooEntryDiffBadge(change) {
    if (change.locked) return '<span class="zd-entry-diff-badge zd-entry-diff-badge-locked">locked</span>';
    if (!change.from) return '<span class="zd-entry-diff-badge zd-entry-diff-badge-new">new</span>';
    return '';
  }

  function zooEntryDiffChangeRow(change) {
    var item = document.createElement('li');
    item.className = 'zd-entry-diff-row';
    var from = String(change.from || '');
    var to = String(change.to || '');
    var split = from && to ? zooEntryDiffSplit(from, to) : null;
    item.innerHTML =
      '<div class="zd-entry-diff-field">' + escapeHtml(zooEntryDiffFieldLabel(change.field)) + zooEntryDiffBadge(change) + '</div>' +
      (from ? zooEntryDiffLineHtml('old', '\u2212', from, split, 'old') : '') +
      zooEntryDiffLineHtml('new', '+', to, split, 'new');
    return item;
  }

  function zooEntryDiffKeyRow(key) {
    var item = document.createElement('li');
    item.className = 'zd-entry-diff-row zd-entry-diff-key';
    item.innerHTML =
      '<div class="zd-entry-diff-field">' + escapeHtml(zooEntryDiffFieldLabel(key.field)) + '<span class="zd-entry-diff-badge">entry</span></div>' +
      '<div class="zd-entry-diff-line"><span class="zd-entry-diff-mark" aria-hidden="true">\u00B7</span>' +
      '<span class="zd-entry-diff-keyterm">' + escapeHtml(key.value) + '</span></div>';
    return item;
  }

  function zooEntryDiffContextRow(entry) {
    var item = document.createElement('li');
    item.className = 'zd-entry-diff-row zd-entry-diff-context';
    item.innerHTML =
      '<div class="zd-entry-diff-field">' + escapeHtml(zooEntryDiffFieldLabel(entry.field)) + '<span class="zd-entry-diff-badge">unchanged</span></div>' +
      '<div class="zd-entry-diff-line"><span class="zd-entry-diff-mark" aria-hidden="true">\u00B7</span>' +
      '<span>' + (entry.value ? escapeHtml(entry.value) : '<span class="zd-entry-diff-empty">(empty)</span>') + '</span></div>';
    return item;
  }

  function zooScrollEntryDiffToHead(list) {
    list.scrollTop = 0;
    var modal = list.closest ? list.closest('.zd-modal') : null;
    if (!modal) return;
    modal.scrollTop = Math.max(0, list.offsetTop - 12);
  }

  function zooRenderEntryDiff(list, changes, unchanged, key) {
    list.textContent = '';
    if (key && key.value) list.appendChild(zooEntryDiffKeyRow(key));
    var rows = Array.isArray(changes) ? changes : [];
    rows.forEach(function(change) { list.appendChild(zooEntryDiffChangeRow(change)); });
    (Array.isArray(unchanged) ? unchanged : []).forEach(function(entry) { list.appendChild(zooEntryDiffContextRow(entry)); });
    list.hidden = !list.childElementCount;
    zooScrollEntryDiffToHead(list);
    return rows.length;
  }

  // -- modal mechanics (mirrors shared/modal.js) --

  var ZOO_TOAST_VISIBLE_MS = 2400;
  var ZOO_TOAST_FADE_MS = 220;
  var zooToastTimer = null;
  var zooToastFadeTimer = null;

  function zooOpenModal(id) {
    var backdrop = document.getElementById(id);
    backdrop.hidden = false;
    var panel = backdrop.querySelector('.zd-modal');
    if (panel) panel.scrollTop = 0;
  }

  function zooCloseModal(id) {
    document.getElementById(id).hidden = true;
  }

  function zooSetModalStatus(id, message, isError) {
    var node = document.getElementById(id);
    if (!node) return;
    node.textContent = message || '';
    node.hidden = !message;
    if (isError) {
      node.classList.add('zd-error');
    } else {
      node.classList.remove('zd-error');
    }
  }

  function zooShowToast(message) {
    var toast = document.getElementById('zoopdog-toast');
    if (!toast) return;
    clearTimeout(zooToastTimer);
    clearTimeout(zooToastFadeTimer);
    toast.textContent = message;
    toast.hidden = false;
    void toast.offsetWidth;
    toast.classList.add('zd-visible');
    zooToastTimer = setTimeout(function() {
      toast.classList.remove('zd-visible');
      zooToastFadeTimer = setTimeout(function() { toast.hidden = true; }, ZOO_TOAST_FADE_MS);
    }, ZOO_TOAST_VISIBLE_MS);
  }

  function zooBindModalDismiss() {
    document.querySelectorAll('.zd-modal-backdrop').forEach(function(backdrop) {
      backdrop.querySelectorAll('[data-zd-modal-cancel]').forEach(function(button) {
        button.addEventListener('click', function() { zooCloseModal(backdrop.id); });
      });
    });
    document.addEventListener('keydown', function(event) {
      if (event.key !== 'Escape') return;
      document.querySelectorAll('.zd-modal-backdrop').forEach(function(backdrop) {
        if (!backdrop.hidden) zooCloseModal(backdrop.id);
      });
    });
  }

  function zooMakeModalDraggable(modalId) {
    var panel = document.querySelector('#' + modalId + ' .zd-modal');
    if (!panel) return;
    var handle = panel.querySelector('h2');
    if (!handle) return;
    handle.classList.add('zd-modal-drag-handle');
    handle.title = 'Drag to move';
    var drag = null;

    handle.addEventListener('pointerdown', function(event) {
      var rect = panel.getBoundingClientRect();
      drag = { pointerId: event.pointerId, offsetX: event.clientX - rect.left, offsetY: event.clientY - rect.top };
      panel.style.position = 'fixed';
      panel.style.margin = '0';
      panel.style.left = rect.left + 'px';
      panel.style.top = rect.top + 'px';
      if (handle.setPointerCapture) handle.setPointerCapture(event.pointerId);
      handle.classList.add('zd-dragging');
    });

    handle.addEventListener('pointermove', function(event) {
      if (!drag || event.pointerId !== drag.pointerId) return;
      var maxLeft = Math.max(window.innerWidth - panel.offsetWidth, 0);
      var maxTop = Math.max(window.innerHeight - panel.offsetHeight, 0);
      panel.style.left = Math.min(Math.max(event.clientX - drag.offsetX, 0), maxLeft) + 'px';
      panel.style.top = Math.min(Math.max(event.clientY - drag.offsetY, 0), maxTop) + 'px';
    });

    function endDrag(event) {
      if (!drag || event.pointerId !== drag.pointerId) return;
      if (handle.releasePointerCapture) handle.releasePointerCapture(event.pointerId);
      handle.classList.remove('zd-dragging');
      drag = null;
    }
    handle.addEventListener('pointerup', endDrag);
    handle.addEventListener('pointercancel', endDrag);
  }

  // -- markup + wiring for the two modals --

  var ZOO_MODAL_IDS = {
    nom: {
      backdrop: 'zoopdog-nom-modal',
      form: 'zoopdog-nom-form',
      title: 'zoopdog-nom-modal-title',
      existingInfo: 'zoopdog-nom-existing-info',
      vi: 'zoopdog-nom-vi',
      nom: 'zoopdog-nom-nom',
      suggestions: 'zoopdog-nom-nom-suggestions',
      explain: 'zoopdog-nom-explain',
      notesRefresh: 'zoopdog-nom-notes-refresh',
      diffPreview: 'zoopdog-nom-diff-preview',
      status: 'zoopdog-nom-form-status',
      saveBtn: 'zoopdog-nom-save-btn',
      confirmBtn: 'zoopdog-nom-confirm-update-btn'
    },
    order: {
      backdrop: 'zoopdog-nom-order-modal',
      form: 'zoopdog-nom-order-form',
      title: 'zoopdog-nom-order-modal-title',
      existingInfo: 'zoopdog-nom-order-existing-info',
      vi: 'zoopdog-nom-order-vi',
      words: 'zoopdog-nom-order-words',
      nom: 'zoopdog-nom-order-nom',
      suggestions: 'zoopdog-nom-order-suggestions',
      current: 'zoopdog-nom-order-current',
      diffPreview: 'zoopdog-nom-order-diff-preview',
      status: 'zoopdog-nom-order-form-status',
      saveBtn: 'zoopdog-nom-order-save-btn',
      confirmBtn: 'zoopdog-nom-order-confirm-btn'
    }
  };

  var zooNomFormState = null;
  var zooOrderState = null;

  function zooRenderLocalActions(vn) {
    if (!ZOO_LOCAL_AVAILABLE) return '';
    var vi = escapeHtml(vn);
    return [
      '<div class="zd-local-actions">',
      '<button type="button" class="zd-local-btn" data-zd-action="add-nom" data-zd-vi="', vi, '">+ Add Ch\u1EEF N\u00F4m</button>',
      '<button type="button" class="zd-local-btn" data-zd-action="set-order" data-zd-vi="', vi, '">Set order</button>',
      '</div>'
    ].join('');
  }

  function zooWireNomForm() {
    var ids = ZOO_MODAL_IDS.nom;
    var guard = zooCreateRaceGuard();
    var nomInput = document.getElementById(ids.nom);
    var explainInput = document.getElementById(ids.explain);
    var nomEdits = zooTrackEdits(nomInput);
    var explainEdits = zooTrackEdits(explainInput);
    var stateFlags = { isUpdate: false };

    zooWireDatalistAutoClear(nomInput, function() { return nomEdits.edited; });

    function resetPreview() {
      document.getElementById(ids.diffPreview).hidden = true;
      document.getElementById(ids.diffPreview).textContent = '';
      document.getElementById(ids.confirmBtn).hidden = true;
      document.getElementById(ids.saveBtn).hidden = false;
      document.getElementById(ids.saveBtn).textContent = stateFlags.isUpdate ? 'Preview update' : 'Save';
    }

    [nomInput, explainInput].forEach(function(input) {
      input.addEventListener('input', resetPreview);
    });

    var nextNotesEngine = zooCreateEngineRotator();
    document.getElementById(ids.notesRefresh).addEventListener('click', function() {
      var vi = document.getElementById(ids.vi).value.trim();
      if (!vi) return;
      var button = document.getElementById(ids.notesRefresh);
      button.disabled = true;
      zooFetchNotesRefresh('nom-notes', vi, nextNotesEngine()).then(function(result) {
        if (result.candidates.length) {
          explainInput.value = result.candidates[0];
          explainEdits.mark();
          resetPreview();
          zooSetModalStatus(ids.status, zooNotesEngineMessage(result.engine, true), false);
        } else {
          zooSetModalStatus(ids.status, zooNotesEngineMessage(result.engine, false), true);
        }
      }).then(null, function() {}).then(function() {
        button.disabled = false;
      });
    });

    function refreshSuggestions(vi) {
      var isCurrent = guard.begin();
      document.getElementById(ids.title).textContent = 'Add Ch\u1EEF N\u00F4m entry';
      document.getElementById(ids.existingInfo).hidden = true;
      stateFlags.isUpdate = false;
      if (!vi) {
        zooFillDatalist(ids.suggestions, []);
        resetPreview();
        return;
      }
      Promise.all([
        zooFetchSuggestions('nom', vi),
        zooFetchSuggestions('nom-notes', vi),
        zooGetJSON('/v1/nom/entry', { vi: vi }).then(null, function() { return { exists: false }; })
      ]).then(function(results) {
        if (!isCurrent()) return;
        var candidates = results[0];
        var notesCandidates = results[1];
        var existing = results[2];
        zooFillDatalist(ids.suggestions, candidates);
        if (!nomEdits.edited) {
          zooSetAutofillDefault(nomInput, candidates.length ? candidates[0] : '');
        }
        if (!explainEdits.edited && notesCandidates.length) {
          explainInput.value = notesCandidates[0];
        }
        if (existing.exists) {
          stateFlags.isUpdate = true;
          document.getElementById(ids.title).textContent = 'Update Ch\u1EEF N\u00F4m entry';
          var notesPart = existing.explain && existing.explain.length ? (' \u2014 notes: ' + existing.explain.join('; ')) : '';
          document.getElementById(ids.existingInfo).textContent = 'Already recorded: ' + (existing.nom || []).join(', ') + notesPart;
          document.getElementById(ids.existingInfo).hidden = false;
        }
        resetPreview();
      });
    }

    var refreshDebounced = zooDebounce(function(vi) { refreshSuggestions(vi); }, 400);

    document.getElementById(ids.vi).addEventListener('input', function() {
      resetPreview();
      nomEdits.reset();
      explainEdits.reset();
      stateFlags.isUpdate = false;
      refreshDebounced(document.getElementById(ids.vi).value.trim());
    });

    function formQuery() {
      var vi = document.getElementById(ids.vi).value.trim();
      var nom = nomInput.value.trim();
      var query = { vi: vi, nom: nom };
      var explain = explainInput.value.trim();
      if (explain) query.explain = explain;
      return { vi: vi, nom: nom, query: query };
    }

    document.getElementById(ids.form).addEventListener('submit', function(event) {
      event.preventDefault();
      var parsed = formQuery();
      if (!parsed.vi || !parsed.nom) {
        zooSetModalStatus(ids.status, 'Vietnamese term and Ch\u1EEF N\u00F4m are both required.', true);
        return;
      }
      if (!stateFlags.isUpdate) {
        zooPost('/v1/nom/entries', parsed.query).then(function(payload) {
          zooCloseModal(ids.backdrop);
          zooShowToast(payload.note || 'Added.');
        }, function(error) {
          zooSetModalStatus(ids.status, error.message, true);
        });
        return;
      }
      var previewQuery = {};
      Object.keys(parsed.query).forEach(function(key) { previewQuery[key] = parsed.query[key]; });
      previewQuery.preview = '1';
      zooPost('/v1/nom/entries', previewQuery).then(function(payload) {
        var changed = zooRenderEntryDiff(
          document.getElementById(ids.diffPreview),
          payload.changes, payload.unchanged, payload.key
        );
        if (!changed) {
          zooSetModalStatus(ids.status, 'Nothing new -- already recorded exactly this.', true);
          document.getElementById(ids.confirmBtn).hidden = true;
          return;
        }
        document.getElementById(ids.saveBtn).hidden = true;
        document.getElementById(ids.confirmBtn).hidden = false;
        zooSetModalStatus(ids.status, '', false);
      }, function(error) {
        zooSetModalStatus(ids.status, error.message, true);
      });
    });

    document.getElementById(ids.confirmBtn).addEventListener('click', function() {
      var parsed = formQuery();
      if (!parsed.vi || !parsed.nom) return;
      zooPost('/v1/nom/entries', parsed.query).then(function(payload) {
        zooCloseModal(ids.backdrop);
        zooShowToast(payload.note || 'Updated.');
      }, function(error) {
        zooSetModalStatus(ids.status, error.message, true);
      });
    });

    zooNomFormState = {
      refresh: refreshSuggestions,
      reset: function() {
        nomEdits.reset();
        explainEdits.reset();
        stateFlags.isUpdate = false;
        document.getElementById(ids.title).textContent = 'Add Ch\u1EEF N\u00F4m entry';
        document.getElementById(ids.existingInfo).hidden = true;
      }
    };
  }

  function zooOpenNomModal(vi) {
    zooBuildModals();
    var ids = ZOO_MODAL_IDS.nom;
    var term = zooTrimSelectionPunctuation(vi);
    zooNomFormState.reset();
    document.getElementById(ids.vi).value = term;
    document.getElementById(ids.nom).value = '';
    delete document.getElementById(ids.nom).dataset.autofillDefault;
    document.getElementById(ids.explain).value = '';
    document.getElementById(ids.title).textContent = 'Add Ch\u1EEF N\u00F4m entry';
    document.getElementById(ids.existingInfo).hidden = true;
    zooSetModalStatus(ids.status, '', false);
    document.getElementById(ids.diffPreview).hidden = true;
    document.getElementById(ids.diffPreview).textContent = '';
    document.getElementById(ids.confirmBtn).hidden = true;
    document.getElementById(ids.saveBtn).hidden = false;
    document.getElementById(ids.saveBtn).textContent = 'Save';
    zooOpenModal(ids.backdrop);
    zooNomFormState.refresh(term);
  }

  function zooWireNomOrderForm() {
    var ids = ZOO_MODAL_IDS.order;
    var nomInput = document.getElementById(ids.nom);
    var viInput = document.getElementById(ids.vi);
    var order = { vi: '', words: [], variants: [], stored: null };
    var token = 0;

    zooWirePickerAutoClear(nomInput);

    function term() { return viInput.value.trim(); }
    function isUpdate() { return order.stored !== null; }

    function resetPreview() {
      document.getElementById(ids.diffPreview).hidden = true;
      document.getElementById(ids.diffPreview).textContent = '';
      document.getElementById(ids.confirmBtn).hidden = true;
      document.getElementById(ids.saveBtn).hidden = false;
    }

    function renderWords() {
      var box = document.getElementById(ids.words);
      box.textContent = '';
      if (order.words.length < 2) { box.hidden = true; return; }
      var label = document.createElement('span');
      label.textContent = 'Ordering applies to one word:';
      box.appendChild(label);
      var current = term();
      order.words.forEach(function(word) {
        var chip = document.createElement('button');
        chip.type = 'button';
        chip.className = 'zd-nom-order-word';
        chip.textContent = word;
        chip.setAttribute('aria-pressed', String(word === current));
        chip.addEventListener('click', function() {
          viInput.value = word;
          refresh();
        });
        box.appendChild(chip);
      });
      box.hidden = false;
    }

    function renderOptions() {
      var list = document.getElementById(ids.suggestions);
      list.textContent = '';
      order.variants.forEach(function(variant) {
        var option = document.createElement('option');
        option.value = variant;
        list.appendChild(option);
      });
      var hint = document.getElementById(ids.current);
      var count = order.variants.length;
      if (count) {
        hint.textContent = 'Currently shown as ruby: ' + order.variants[0] + ' \u00B7 ' + count + ' rendering' + (count === 1 ? '' : 's') + ' known';
      } else if (order.vi) {
        hint.textContent = 'No renderings are known for this term; anything entered here will be pinned as its first.';
      } else {
        hint.textContent = '';
      }
      hint.hidden = !hint.textContent;
    }

    function refresh() {
      var vi = term();
      var myToken = (token += 1);

      order.vi = vi;
      order.variants = [];
      order.stored = null;
      nomInput.value = '';
      document.getElementById(ids.suggestions).textContent = '';
      document.getElementById(ids.existingInfo).hidden = true;
      document.getElementById(ids.title).textContent = 'Set Ch\u1EEF N\u00F4m order';
      document.getElementById(ids.current).hidden = true;
      zooSetModalStatus(ids.status, '', false);
      resetPreview();
      renderWords();

      if (!vi) return;

      zooGetJSON('/v1/nom/order', { vi: vi, scope: 'global' }).then(function(payload) {
        if (myToken !== token) return;
        order.variants = payload.variants || [];
        order.stored = payload.exists ? (payload.order || []) : null;
        renderOptions();
        if (isUpdate()) {
          document.getElementById(ids.title).textContent = 'Update Ch\u1EEF N\u00F4m order';
          document.getElementById(ids.existingInfo).textContent = 'Already recorded: ' + order.stored.join(', ');
          document.getElementById(ids.existingInfo).hidden = false;
          nomInput.value = order.stored[0] || '';
        }
        resetPreview();
      }, function(error) {
        if (myToken !== token) return;
        zooSetModalStatus(ids.status, error.message, true);
      });
    }

    var refreshDebounced = zooDebounce(function() { refresh(); }, 400);

    viInput.addEventListener('input', function() {
      renderWords();
      resetPreview();
      refreshDebounced();
    });

    nomInput.addEventListener('input', function() {
      resetPreview();
      zooSetModalStatus(ids.status, '', false);
    });

    function query() {
      return { vi: term(), nom: nomInput.value.trim(), scope: 'global' };
    }

    document.getElementById(ids.form).addEventListener('submit', function(event) {
      event.preventDefault();
      var q = query();
      if (!q.vi || !q.nom) return;
      var previewQuery = { vi: q.vi, nom: q.nom, scope: q.scope, preview: '1' };
      zooPost('/v1/nom/order', previewQuery).then(function(payload) {
        var changed = zooRenderEntryDiff(
          document.getElementById(ids.diffPreview),
          payload.changes, payload.unchanged, payload.key
        );
        if (!changed) {
          zooSetModalStatus(ids.status, 'Nothing to change -- already the preferred rendering.', true);
          document.getElementById(ids.confirmBtn).hidden = true;
          return;
        }
        document.getElementById(ids.saveBtn).hidden = true;
        document.getElementById(ids.confirmBtn).hidden = false;
        zooSetModalStatus(ids.status, '', false);
      }, function(error) {
        zooSetModalStatus(ids.status, error.message, true);
      });
    });

    document.getElementById(ids.confirmBtn).addEventListener('click', function() {
      var q = query();
      if (!q.vi || !q.nom) return;
      zooPost('/v1/nom/order', q).then(function(payload) {
        zooCloseModal(ids.backdrop);
        zooShowToast(payload.note || 'Saved.');
      }, function(error) {
        zooSetModalStatus(ids.status, error.message, true);
      });
    });

    zooOrderState = {
      setWords: function(words) { order.words = words; },
      refresh: refresh
    };
  }

  function zooOpenNomOrderModal(vi) {
    zooBuildModals();
    var ids = ZOO_MODAL_IDS.order;
    var selection = zooTrimSelectionPunctuation(vi);
    zooOrderState.setWords(selection.split(/\s+/).filter(Boolean));
    document.getElementById(ids.vi).value = selection;
    zooOpenModal(ids.backdrop);
    zooOrderState.refresh();
  }

  function zooBuildModals() {
    if (document.getElementById(ZOO_MODAL_IDS.nom.backdrop)) return;

    var nomIds = ZOO_MODAL_IDS.nom;
    var nomHtml = [
      '<div id="', nomIds.backdrop, '" class="zd-modal-backdrop" hidden>',
      '<form id="', nomIds.form, '" class="zd-modal">',
      '<h2 id="', nomIds.title, '">Add Ch\u1EEF N\u00F4m entry</h2>',
      '<p id="', nomIds.existingInfo, '" class="zd-modal-hint" hidden></p>',
      '<label>Vietnamese term<input id="', nomIds.vi, '" type="text" required></label>',
      '<label>Ch\u1EEF N\u00F4m',
      '<input id="', nomIds.nom, '" type="text" required list="', nomIds.suggestions, '">',
      '<datalist id="', nomIds.suggestions, '"></datalist>',
      '</label>',
      '<label>Notes',
      '<span class="zd-field-row">',
      '<input id="', nomIds.explain, '" type="text">',
      '<button type="button" id="', nomIds.notesRefresh, '" class="zd-field-button" title="Re-translate -- each click asks the next engine in turn">\u21BB</button>',
      '</span>',
      '</label>',
      '<ul id="', nomIds.diffPreview, '" class="zd-entry-diff-list" hidden></ul>',
      '<p id="', nomIds.status, '" class="zd-modal-status" hidden></p>',
      '<div class="zd-modal-actions">',
      '<button type="button" data-zd-modal-cancel>Cancel</button>',
      '<button type="submit" id="', nomIds.saveBtn, '">Save</button>',
      '<button type="button" id="', nomIds.confirmBtn, '" hidden>Confirm update</button>',
      '</div>',
      '</form>',
      '</div>'
    ].join('');

    var orderIds = ZOO_MODAL_IDS.order;
    var orderHtml = [
      '<div id="', orderIds.backdrop, '" class="zd-modal-backdrop" hidden>',
      '<form id="', orderIds.form, '" class="zd-modal">',
      '<h2 id="', orderIds.title, '">Set Ch\u1EEF N\u00F4m order</h2>',
      '<p class="zd-modal-hint">The rendering picked here leads the list, so it is the one shown as ruby.</p>',
      '<p id="', orderIds.existingInfo, '" class="zd-modal-hint" hidden></p>',
      '<label>Vietnamese term<input id="', orderIds.vi, '" type="text" required autocomplete="off"></label>',
      '<p id="', orderIds.words, '" class="zd-nom-order-words" hidden></p>',
      '<label>Preferred rendering',
      '<input id="', orderIds.nom, '" type="text" class="zd-nom-order-pick" required list="', orderIds.suggestions, '" autocomplete="off">',
      '<datalist id="', orderIds.suggestions, '"></datalist>',
      '</label>',
      '<p id="', orderIds.current, '" class="zd-modal-hint" hidden></p>',
      '<ul id="', orderIds.diffPreview, '" class="zd-entry-diff-list" hidden></ul>',
      '<p id="', orderIds.status, '" class="zd-modal-status" hidden></p>',
      '<div class="zd-modal-actions">',
      '<button type="button" data-zd-modal-cancel>Cancel</button>',
      '<button type="submit" id="', orderIds.saveBtn, '">Preview</button>',
      '<button type="button" id="', orderIds.confirmBtn, '" hidden>Confirm update</button>',
      '</div>',
      '</form>',
      '</div>'
    ].join('');

    var toastHtml = '<div id="zoopdog-toast" class="zd-toast" hidden></div>';

    var container = document.createElement('div');
    container.id = 'zoopdog-userscript-modals';
    container.innerHTML = nomHtml + orderHtml + toastHtml;
    document.body.appendChild(container);
    container.addEventListener('mousedown', function(event) { event.stopPropagation(); });

    zooBindModalDismiss();
    zooMakeModalDraggable(ZOO_MODAL_IDS.nom.backdrop);
    zooMakeModalDraggable(ZOO_MODAL_IDS.order.backdrop);
    zooWireNomForm();
    zooWireNomOrderForm();
  }

  function addStyle(css) {
    if (typeof GM_addStyle === 'function') {
      GM_addStyle(css);
      return;
    }

    if (typeof GM !== 'undefined' && GM && typeof GM.addStyle === 'function') {
      GM.addStyle(css);
      return;
    }

    var head = document.getElementsByTagName('head')[0];
    if (!head) {
      return;
    }

    var style = document.createElement('style');
    style.type = 'text/css';
    style.textContent = css;
    head.appendChild(style);
  }

  function normalizeLookup(value) {
    return String(value || '')
      .replace(/[Đ\u00D0]/gu, 'đ')
      .normalize('NFC')
      .toLocaleLowerCase('vi-VN')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function escapeHtml(value) {
    return String(value || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function lookupContext(context) {
    var split = String(context || '').trim().split(/\s+/).filter(Boolean);
    var limit = Math.min(split.length, ZOO_MAX_WORDS);

    for (var i = limit; i > 0; i--) {
      var candidate = normalizeLookup(split.slice(0, i).join(' '));
      if (ZOO_DICTIONARY[candidate]) {
        return {
          key: candidate,
          wordCount: i,
          results: ZOO_DICTIONARY[candidate]
        };
      }
    }

    return null;
  }

  function elementContainsTextNode(element, textNode) {
    if (!element || !textNode || !textNode.parentNode) {
      return false;
    }
    return element === textNode.parentNode || element.contains(textNode.parentNode);
  }

  function isExcludedTarget(target) {
    if (!target || target.nodeType !== Node.ELEMENT_NODE) {
      return false;
    }

    return !!target.closest(
      '#zoopdog-userscript-popup, #zoopdog-userscript-canvas, #zoopdog-userscript-modals, input, textarea, select, option, button, script, style, [contenteditable="true"]'
    );
  }

  function getEventPoint(event) {
    var touch = null;

    if (event.changedTouches && event.changedTouches.length) {
      touch = event.changedTouches[0];
    } else if (event.touches && event.touches.length) {
      touch = event.touches[0];
    }

    if (touch) {
      return {x: touch.clientX, y: touch.clientY};
    }

    if (typeof event.clientX === 'number' && typeof event.clientY === 'number') {
      return {x: event.clientX, y: event.clientY};
    }

    return null;
  }

  function Highlighter() {
    this.highlights = [];
    this.padding = 5;
    this.locked = false;
    this.canvas = document.createElement('canvas');
    this.canvas.id = 'zoopdog-userscript-canvas';
    this.canvas.style.width = '100%';
    this.canvas.style.height = '100%';
    this.canvas.style.position = 'fixed';
    this.canvas.style.left = 0;
    this.canvas.style.top = '1px';
    this.canvas.style.zIndex = 2147483645;
    this.canvas.style.pointerEvents = 'none';
    document.body.appendChild(this.canvas);
    this.context = this.canvas.getContext('2d');
    this.resize();
  }

  Highlighter.prototype.resize = function() {
    this.canvas.width = window.innerWidth;
    this.canvas.height = window.innerHeight;
  };

  Highlighter.prototype.on = function(node, begin, howManyWords) {
    if (this.highlights.length) {
      this.off();
    }
    if (node === undefined) {
      return true;
    }

    var words = 0;
    var prevChar = '';
    var i;
    for (i = begin; i < node.data.length; i++) {
      if (node.data[i] === ' ') {
        if (prevChar && zdIsWordChar(prevChar)) {
          words++;
        }
      } else if (!zdIsWordChar(node.data[i])) {
        break;
      }

      if (words === howManyWords) {
        break;
      }

      prevChar = node.data[i];
    }

    if (i === begin) {
      return true;
    }

    if (node.data[begin] === ' ') {
      begin++;
    }

    var range = new Range();
    range.setStart(node, begin);
    range.setEnd(node, i);
    this.highlights = Array.from(range.getClientRects());

    this.context.beginPath();
    for (var j = 0; j < this.highlights.length; j++) {
      var hl = this.highlights[j];
      this.context.rect(
        hl.left - this.padding,
        hl.top - this.padding,
        hl.width + (this.padding * 2),
        hl.height + (this.padding * 2)
      );
      this.context.globalAlpha = 0.25;
      this.context.fillStyle = '#B6638F';
      this.context.fill();
    }
  };

  Highlighter.prototype.off = function() {
    if (this.locked) {
      return true;
    }
    this.context.beginPath();
    this.context.setTransform(1, 0, 0, 1, 0, 0);
    this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
    this.context.globalAlpha = 0;
    this.highlights = [];
  };

  Highlighter.prototype.toggleLock = function() {
    if (this.locked) {
      this.locked = false;
      this.off();
    } else if (this.highlights.length) {
      this.locked = true;
    }
  };

  function ResultPopup() {
    this.container = document.createElement('div');
    this.container.id = 'zoopdog-userscript-popup';
    this.container.addEventListener('mousedown', function(event) { event.stopPropagation(); });
    this.container.addEventListener('scroll', function(event) { event.stopPropagation(); });

    this.lockIcon = document.createElement('div');
    this.lockIcon.id = 'zoopdog-userscript-popup-lock-icon';
    this.lockIcon.textContent = '📌';

    this.body = document.createElement('div');
    this.body.id = 'zoopdog-userscript-popup-body';
    this.container.appendChild(this.lockIcon);
    this.container.appendChild(this.body);
    document.body.appendChild(this.container);
    this.locked = false;
  }

  ResultPopup.prototype.populate = function(results) {
    this.body.innerHTML = results.map(renderDefinition).join('');
    drawTonesAndGradients();
  };

  ResultPopup.prototype.show = function(rect) {
    this.container.style.visibility = 'visible';
    this.container.style.left = (rect.left - 20) + 'px';
    this.container.style.top = rect.bottom + 'px';
    this.container.style.bottom = 'auto';

    var popupDimensions = this.container.getBoundingClientRect();
    var rightEdge = popupDimensions.right;
    if (rightEdge > window.innerWidth) {
      var xDif = rightEdge - window.innerWidth;
      this.container.style.left = (parseInt(this.container.style.left, 10) - xDif - 20) + 'px';
    }

    if (rect.top > window.innerHeight / 2) {
      var yDif = window.innerHeight - rect.top;
      this.container.style.top = 'auto';
      this.container.style.bottom = (yDif + 10) + 'px';
    }

    popupDimensions = this.container.getBoundingClientRect();
    if (popupDimensions.left < 20) {
      this.container.style.left = '20px';
    }
  };

  ResultPopup.prototype.hide = function() {
    if (this.locked) {
      return true;
    }
    this.container.style.visibility = 'hidden';
  };

  ResultPopup.prototype.toggleLock = function() {
    if (this.locked) {
      this.locked = false;
      this.lockIcon.style.visibility = 'hidden';
      this.hide();
    } else if (this.container.style.visibility === 'visible') {
      this.locked = true;
      this.lockIcon.style.visibility = 'visible';
    }
  };

  function renderDefinition(entry) {
    var vn = entry[0];
    var definitions = entry[1];
    var pronunciation = renderPronunciation(vn);

    return [
      '<div class="zd-definition">',
      '<h1>', escapeHtml(vn), '</h1>',
      '<div class="zd-pronunciation">', pronunciation, '</div>',
      '<ul>',
      renderDefinitionItems(definitions),
      '</ul>',
      zooRenderLocalActions(vn),
      '</div>'
    ].join('');
  }

  function renderDefinitionItems(definitions) {
    var html = [];
    var pendingCjkTokens = [];

    function flushCjkTokens() {
      if (!pendingCjkTokens.length) {
        return;
      }

      chunkCjkTokens(pendingCjkTokens).forEach(function(chunk) {
        html.push('<li class="zoopdog-cjk-def">' + chunk.map(escapeHtml).join(' | ') + '</li>');
      });
      pendingCjkTokens = [];
    }

    definitions.forEach(function(item) {
      if (isCjkDefinition(item)) {
        pendingCjkTokens = pendingCjkTokens.concat(extractCjkTokens(item[0]));
        pendingCjkTokens = Array.from(new Set(pendingCjkTokens));
        return;
      }

      flushCjkTokens();
      html.push(renderDefinitionItem(item));
    });

    flushCjkTokens();
    return html.join('');
  }

  function isCjkDefinition(item) {
    return !item[1] && ZOO_CJK_RE.test(item[0]) && !/[A-Za-z]/.test(item[0]);
  }

  function extractCjkTokens(value) {
    return Array.from(new Set(String(value || '').match(ZOO_CJK_SEQUENCE_RE) || []));
  }

  function chunkCjkTokens(tokens) {
    var chunks = [];
    var current = [];
    var currentLength = 0;

    tokens.forEach(function(token) {
      var tokenLength = Array.from(token).length;
      var extraLength = current.length ? tokenLength + 3 : tokenLength;

      if (current.length && currentLength + extraLength > ZOO_SETTINGS.cjkDefinitionLineLength) {
        chunks.push(current);
        current = [];
        currentLength = 0;
        extraLength = tokenLength;
      }

      current.push(token);
      currentLength += extraLength;
    });

    if (current.length) {
      chunks.push(current);
    }

    return chunks;
  }

  function renderDefinitionItem(item) {
    var definition = escapeHtml(item[0]);
    var pos = escapeHtml(item[1]);
    if (pos) {
      return '<li><span class="zoopdog-pos">' + pos + '</span> ' + definition + '</li>';
    }
    return '<li>' + definition + '</li>';
  }

  function renderPronunciation(word) {
    try {
      var byDialect = pronunciationGuide(word);
      var result = byDialect[ZOO_SETTINGS.dialect] || byDialect.hanoi;
      return result && result.zd ? result.zd : escapeHtml(word);
    } catch (error) {
      return escapeHtml(word);
    }
  }

  function main() {
    if (!document.body) {
      window.setTimeout(main, 50);
      return;
    }

    addStyle("__ZOOPDOG_CSS__");
    zooProbeLocalMode();

    var highlighter = new Highlighter();
    var popup = new ResultPopup();
    var oldWord = null;

    popup.body.addEventListener('click', function(event) {
      var button = event.target && event.target.closest ? event.target.closest('[data-zd-action]') : null;
      if (!button) return;
      event.preventDefault();
      var action = button.getAttribute('data-zd-action');
      var vi = button.getAttribute('data-zd-vi') || '';
      if (action === 'add-nom') {
        zooOpenNomModal(vi);
      } else if (action === 'set-order') {
        zooOpenNomOrderModal(vi);
      }
    });

    function clearActiveResult() {
      highlighter.off();
      popup.hide();
    }

    function mainListener(event, clearOnMiss) {
      if (popup.locked || isExcludedTarget(event.target)) {
        return true;
      }

      var mouse = getEventPoint(event);
      if (!mouse) {
        return true;
      }

      if (highlighter.highlights.length && mouseInRects(mouse, highlighter.highlights)) {
        return true;
      }

      var origin = getWordAndContext(mouse);
      var element = document.elementFromPoint(mouse.x, mouse.y);

      if (!origin || !origin.word || !elementContainsTextNode(element, origin.node)) {
        if (clearOnMiss) {
          clearActiveResult();
        }
        return true;
      }

      clearActiveResult();

      if (origin.word === oldWord) {
        return true;
      }

      oldWord = origin.word;
      var lookup = lookupContext(origin.context);
      if (!lookup) {
        window.setTimeout(function() {
          oldWord = null;
        }, ZOO_SETTINGS.oldWordResetMs);
        return true;
      }

      highlighter.on(origin.node, origin.begin, lookup.wordCount);
      popup.populate(lookup.results);
      popup.show(highlighter.highlights[0] || {
        left: mouse.x,
        right: mouse.x,
        top: mouse.y,
        bottom: mouse.y
      });

      window.setTimeout(function() {
        oldWord = null;
      }, ZOO_SETTINGS.oldWordResetMs);

      return true;
    }

    window.addEventListener('resize', function() {
      highlighter.resize();
      clearActiveResult();
    });

    var lastTouchTime = 0;
    var touchMoved = false;
    var pointerTouchMoved = false;

    window.addEventListener('scroll', clearActiveResult, true);
    window.addEventListener('mouseout', function() {
      if (Date.now() - lastTouchTime > 700) {
        clearActiveResult();
      }
    });

    function touchListener(event) {
      lastTouchTime = Date.now();
      if (touchMoved) {
        touchMoved = false;
        return true;
      }
      return mainListener(event, true);
    }

    function clickListener(event) {
      if (Date.now() - lastTouchTime < 700) {
        return true;
      }
      return mainListener(event, true);
    }

    if ('PointerEvent' in window) {
      window.addEventListener('pointerdown', function(event) {
        if (event.pointerType === 'touch') {
          lastTouchTime = Date.now();
          pointerTouchMoved = false;
        }
      }, {passive: true});

      window.addEventListener('pointermove', function(event) {
        if (event.pointerType === 'touch') {
          lastTouchTime = Date.now();
          pointerTouchMoved = true;
          clearActiveResult();
          return;
        }

        if (event.pointerType === 'mouse' || event.pointerType === 'pen') {
          mainListener(event, false);
        }
      }, {passive: true});

      window.addEventListener('pointerup', function(event) {
        if (event.pointerType === 'touch') {
          lastTouchTime = Date.now();
        }

        if (event.pointerType === 'touch' && pointerTouchMoved) {
          pointerTouchMoved = false;
          return true;
        }
        mainListener(event, true);
      }, {passive: true});
    } else {
      window.addEventListener('mousemove', function(event) {
        mainListener(event, false);
      });

      window.addEventListener('touchstart', function() {
        touchMoved = false;
      }, {passive: true});

      window.addEventListener('touchmove', function() {
        touchMoved = true;
        clearActiveResult();
      }, {passive: true, capture: true});

      window.addEventListener('touchend', touchListener, {passive: true});
      window.addEventListener('click', clickListener);
    }

    window.addEventListener('keydown', function(event) {
      if (event.which === 16) {
        highlighter.toggleLock();
        popup.toggleLock();
      }
    });
  }

  main();
})();
