// ==UserScript==
// @name        Zoopdog Popup Dictionary__ZOOPDOG_NAME_SUFFIX__
// @description Vietnamese-English popup dictionary with Zoopdog pronunciation guide
// @author      Zoopdog Contributors
// @namespace   https://github.com/tabidots/zoopdog
// @match       *://*/*
// @grant       GM_addStyle__ZOOPDOG_LOCAL_GRANTS__
// @run-at      document-idle
// @version     __ZOOPDOG_VERSION__
// @updateURL   __ZOOPDOG_UPDATE_URL__
// @downloadURL __ZOOPDOG_DOWNLOAD_URL__
// ==/UserScript==

(function() {
__ZOOPDOG_RUNTIME_SOURCES__

  // Generated by scripts/build-popupdict-userscript.js from zd-extension/db_src/vnedict2.json.
  // Also merges zd-extension/db_src/user_nom_entries.jsonc when present.
  // Dictionary keys embedded: __ZOOPDOG_KEY_COUNT__
  var ZOO_DICTIONARY = {"__ZOOPDOG_DICTIONARY__": true};
  var ZOO_MAX_WORDS = __ZOOPDOG_MAX_WORDS__;

  var ZOO_SETTINGS = {
    cjkDefinitionLineLength: 18,
    oldWordResetMs: 500
  };

  var ZOO_CJK_RE = /[\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF\u{20000}-\u{323AF}]/u;
  var ZOO_CJK_SEQUENCE_RE = /[\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF\u{20000}-\u{323AF}]+/gu;

  // Local-mode (add/edit Chu Nom entries via the book-translator reader server) lives in
  // scripts/userscript/popupdict-local.runtime.js -- see docs/local-mode.md. It is only
  // concatenated into the -local build; the calls below are guarded so this file stays
  // fully functional without it.

  function addStyle(css) {
    if (typeof GM_addStyle === 'function') {
      GM_addStyle(css);
      return;
    }

    if (typeof GM !== 'undefined' && GM && typeof GM.addStyle === 'function') {
      GM.addStyle(css);
      return;
    }

    var head = document.getElementsByTagName('head')[0];
    if (!head) {
      return;
    }

    var style = document.createElement('style');
    style.type = 'text/css';
    style.textContent = css;
    head.appendChild(style);
  }

  // Sites that opt into a Trusted Types CSP (YouTube among them) throw
  // "Failed to set the 'innerHTML' property ... requires 'TrustedHTML'
  // assignment" on a plain string assignment, which aborted mainListener
  // before popup.show() ever ran -- the popup looked "impossible to show"
  // on those sites when the actual failure was this uncaught exception.
  // Every caller here already builds its HTML through escapeHtml, so the
  // policy is a pass-through, not a sanitizer.
  var zooTrustedTypesPolicy;

  function zooSetHTML(el, html) {
    if (typeof zooTrustedTypesPolicy === 'undefined') {
      zooTrustedTypesPolicy = null;
      if (typeof window.trustedTypes !== 'undefined' && window.trustedTypes.createPolicy) {
        try {
          zooTrustedTypesPolicy = window.trustedTypes.createPolicy('zoopdog-userscript', {
            createHTML: function(value) { return value; }
          });
        } catch (error) {
          zooTrustedTypesPolicy = null;
        }
      }
    }

    el.innerHTML = zooTrustedTypesPolicy ? zooTrustedTypesPolicy.createHTML(html) : html;
  }

  function normalizeLookup(value) {
    return String(value || '')
      .replace(/[Đ\u00D0]/gu, 'đ')
      .normalize('NFC')
      .toLocaleLowerCase('vi-VN')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function escapeHtml(value) {
    return String(value || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function lookupContext(context) {
    var split = String(context || '').trim().split(/\s+/).filter(Boolean);
    var limit = Math.min(split.length, ZOO_MAX_WORDS);

    for (var i = limit; i > 0; i--) {
      var candidate = normalizeLookup(split.slice(0, i).join(' '));
      if (ZOO_DICTIONARY[candidate]) {
        return {
          key: candidate,
          wordCount: i,
          results: ZOO_DICTIONARY[candidate]
        };
      }
    }

    return null;
  }

  // Element.contains() never crosses an open shadow boundary -- a video-caption or
  // translation-overlay widget (Eudict/欧路翻译, Immersive Translate) renders its actual text
  // inside one (see docs/build.md), so a plain contains() call from outside always answers
  // false for it even when the node is genuinely part of that widget's rendered tree. Walking
  // through `.host` wherever `.parentNode` runs out is the same climb Node.isConnected does
  // internally to cross that boundary.
  function zdContains(ancestor, node) {
    for (var current = node; current; current = current.parentNode || current.host) {
      if (current === ancestor) {
        return true;
      }
    }
    return false;
  }

  function elementContainsTextNode(element, textNode) {
    if (!element || !textNode || !textNode.parentNode) {
      return false;
    }
    return zdContains(element, textNode.parentNode);
  }

  function isExcludedTarget(target) {
    if (!target || target.nodeType !== Node.ELEMENT_NODE) {
      return false;
    }

    return !!target.closest(
      '#zoopdog-userscript-popup, #zoopdog-userscript-canvas, #zoopdog-userscript-modals, #zoopdog-userscript-selection-bar, input, textarea, select, option, button, script, style, [contenteditable="true"]'
    );
  }

  function getEventPoint(event) {
    var touch = null;

    if (event.changedTouches && event.changedTouches.length) {
      touch = event.changedTouches[0];
    } else if (event.touches && event.touches.length) {
      touch = event.touches[0];
    }

    if (touch) {
      return {x: touch.clientX, y: touch.clientY};
    }

    if (typeof event.clientX === 'number' && typeof event.clientY === 'number') {
      return {x: event.clientX, y: event.clientY};
    }

    return null;
  }

  function Highlighter() {
    this.highlights = [];
    this.padding = 5;
    this.locked = false;
    this.canvas = document.createElement('canvas');
    this.canvas.id = 'zoopdog-userscript-canvas';
    this.canvas.style.width = '100%';
    this.canvas.style.height = '100%';
    this.canvas.style.position = 'fixed';
    this.canvas.style.left = 0;
    this.canvas.style.top = '1px';
    this.canvas.style.zIndex = 2147483645;
    this.canvas.style.pointerEvents = 'none';
    document.body.appendChild(this.canvas);
    this.context = this.canvas.getContext('2d');
    this.resize();
  }

  Highlighter.prototype.resize = function() {
    this.canvas.width = window.innerWidth;
    this.canvas.height = window.innerHeight;
  };

  Highlighter.prototype.on = function(node, begin, howManyWords) {
    if (this.highlights.length) {
      this.off();
    }
    if (node === undefined) {
      return true;
    }
    // Remembered so the window-level scroll listener can tell "the article
    // scrolled, this highlight is stale" from "some unrelated widget on the
    // page fired a scroll event" -- see that listener below.
    this.node = node;

    var boundary = zdContainerBoundary(node);
    var ranges = [];
    var words = 0;
    var prevChar = '';
    var curNode = node;
    var curBegin = begin;

    // A match can straddle more than one <ruby>-wrapped word (see zd-words.js), so keep
    // building ranges into whatever text node follows once this one runs out, rather than
    // stopping at this node's own end.
    while (curNode && words < howManyWords) {
      var data = curNode.data;
      var i;
      for (i = curBegin; i < data.length; i++) {
        if (/\s/.test(data[i])) {
          if (prevChar && zdIsWordChar(prevChar)) {
            words++;
          }
        } else if (!zdIsWordChar(data[i])) {
          break;
        }

        if (words === howManyWords) {
          break;
        }

        prevChar = data[i];
      }

      if (i === curBegin) {
        break;
      }

      var rangeBegin = curBegin;
      if (/\s/.test(data[rangeBegin])) {
        rangeBegin++;
      }
      if (rangeBegin < i) {
        var range = new Range();
        range.setStart(curNode, rangeBegin);
        range.setEnd(curNode, i);
        ranges.push(range);
      }

      if (words >= howManyWords || i < data.length) {
        break;
      }

      var nextNode = zdNextTextNode(curNode, boundary);
      if (!nextNode) {
        break;
      }
      if (prevChar && zdIsWordChar(prevChar)) {
        // The node boundary itself stands in for the space between words.
        words++;
        prevChar = '';
        if (words === howManyWords) {
          break;
        }
      }
      curNode = nextNode;
      curBegin = 0;
    }

    if (!ranges.length) {
      return true;
    }

    this.highlights = ranges.reduce(function(rects, range) {
      return rects.concat(Array.from(range.getClientRects()));
    }, []);

    this.context.beginPath();
    for (var j = 0; j < this.highlights.length; j++) {
      var hl = this.highlights[j];
      this.context.rect(
        hl.left - this.padding,
        hl.top - this.padding,
        hl.width + (this.padding * 2),
        hl.height + (this.padding * 2)
      );
      this.context.globalAlpha = 0.25;
      this.context.fillStyle = '#B6638F';
      this.context.fill();
    }
  };

  Highlighter.prototype.off = function() {
    if (this.locked) {
      return true;
    }
    this.context.beginPath();
    this.context.setTransform(1, 0, 0, 1, 0, 0);
    this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
    this.context.globalAlpha = 0;
    this.highlights = [];
    this.node = null;
  };

  Highlighter.prototype.toggleLock = function() {
    if (this.locked) {
      this.locked = false;
      this.off();
    } else if (this.highlights.length) {
      this.locked = true;
    }
  };

  function ResultPopup() {
    this.container = document.createElement('div');
    this.container.id = 'zoopdog-userscript-popup';
    this.container.addEventListener('mousedown', function(event) { event.stopPropagation(); });
    this.container.addEventListener('scroll', function(event) { event.stopPropagation(); });

    this.lockIcon = document.createElement('div');
    this.lockIcon.id = 'zoopdog-userscript-popup-lock-icon';
    this.lockIcon.textContent = '📌';

    this.body = document.createElement('div');
    this.body.id = 'zoopdog-userscript-popup-body';
    this.container.appendChild(this.lockIcon);
    this.container.appendChild(this.body);
    document.body.appendChild(this.container);
    this.locked = false;
    this.bindDrag();
  }

  var PIN_POSITION_KEY = 'zoopdog-popup-pin-position';

  function readPinPosition() {
    try {
      var raw = typeof GM_getValue === 'function'
        ? GM_getValue(PIN_POSITION_KEY, null)
        : window.localStorage.getItem(PIN_POSITION_KEY);
      var pos = raw ? JSON.parse(raw) : null;
      if (pos && isFinite(pos.left) && isFinite(pos.top)) return pos;
    } catch (error) { /* no stored position */ }
    return null;
  }

  function writePinPosition(pos) {
    var raw = JSON.stringify(pos);
    try {
      if (typeof GM_setValue === 'function') GM_setValue(PIN_POSITION_KEY, raw);
      else window.localStorage.setItem(PIN_POSITION_KEY, raw);
    } catch (error) { /* position just is not remembered */ }
  }

  ResultPopup.prototype.moveTo = function(left, top) {
    var box = this.container.getBoundingClientRect();
    var style = this.container.style;
    style.left = Math.max(0, Math.min(left, window.innerWidth - box.width)) + 'px';
    style.top = Math.max(0, Math.min(top, window.innerHeight - box.height)) + 'px';
    style.bottom = 'auto';
  };

  // The pin icon is the drag handle while the popup is locked; the spot is remembered.
  ResultPopup.prototype.bindDrag = function() {
    var popup = this;
    this.lockIcon.addEventListener('mousedown', function(event) {
      if (!popup.locked || event.button !== 0) return;
      event.preventDefault();
      var box = popup.container.getBoundingClientRect();
      var dx = event.clientX - box.left;
      var dy = event.clientY - box.top;
      function onMove(moveEvent) {
        popup.moveTo(moveEvent.clientX - dx, moveEvent.clientY - dy);
      }
      function onUp() {
        document.removeEventListener('mousemove', onMove, true);
        document.removeEventListener('mouseup', onUp, true);
        var end = popup.container.getBoundingClientRect();
        writePinPosition({left: end.left, top: end.top});
      }
      document.addEventListener('mousemove', onMove, true);
      document.addEventListener('mouseup', onUp, true);
    });
  };

  ResultPopup.prototype.populate = function(results) {
    zooSetHTML(this.body, results.map(renderDefinition).join(''));
  };

  ResultPopup.prototype.show = function(rect) {
    var style = this.container.style;
    var margin = 8;
    var viewWidth = document.documentElement.clientWidth || window.innerWidth;
    var viewHeight = window.innerHeight;
    var below = viewHeight - rect.bottom - margin;
    var above = rect.top - margin;
    var placeAbove = below < 160 && above > below;
    var room = Math.max(80, placeAbove ? above : below);

    // Fit the popup to the viewport: cap its size, then clamp its position.
    style.maxWidth = Math.min(400, viewWidth - 2 * margin) + 'px';
    style.maxHeight = Math.min(Math.max(280, viewHeight * 0.5), room) + 'px';
    style.visibility = 'visible';

    // A fixed box shrink-wraps to the space right of `left`, so measure its
    // natural width at the left edge before clamping.
    style.left = '0px';
    var box = this.container.getBoundingClientRect();
    var left = Math.max(margin, Math.min(rect.left - 20, viewWidth - box.width - margin));
    style.left = left + 'px';
    if (placeAbove) {
      style.top = 'auto';
      style.bottom = (viewHeight - rect.top + 4) + 'px';
    } else {
      style.top = rect.bottom + 'px';
      style.bottom = 'auto';
    }
  };

  ResultPopup.prototype.hide = function() {
    if (this.locked) {
      return true;
    }
    this.container.style.visibility = 'hidden';
  };

  ResultPopup.prototype.toggleLock = function() {
    if (this.locked) {
      this.locked = false;
      this.lockIcon.style.visibility = 'hidden';
      this.hide();
    } else if (this.container.style.visibility === 'visible') {
      this.locked = true;
      this.lockIcon.style.visibility = 'visible';
      var pos = readPinPosition();
      if (pos) this.moveTo(pos.left, pos.top);
    }
  };

  function renderDefinition(entry) {
    // `entry` is `[headwords, senses]` -- see scripts/build-popupdict-userscript.js and the
    // shared grouping transform in scripts/lib/dictionary-identity.js. `headwords` is every
    // display variant a normalized key collided on (`Ba Lê` / `ba lê`), ordered by first
    // source occurrence; `vn` (the primary headword) is `headwords[0]` and is what a local
    // "add Chu Nom"/"set order" action still keys on.
    var headwords = entry[0];
    var definitions = entry[1];
    var vn = headwords[0];

    return [
      '<div class="zd-definition">',
      '<h1>', headwords.map(escapeHtml).join(' / '), '</h1>',
      '<ul>',
      renderDefinitionItems(definitions),
      '</ul>',
      typeof zooRenderLocalActions === 'function' ? zooRenderLocalActions(vn) : '',
      '</div>'
    ].join('');
  }

  function renderDefinitionItems(definitions) {
    var html = [];
    var pendingCjkTokens = [];

    function flushCjkTokens() {
      if (!pendingCjkTokens.length) {
        return;
      }

      chunkCjkTokens(pendingCjkTokens).forEach(function(chunk) {
        html.push('<li class="zoopdog-cjk-def">' + chunk.map(escapeHtml).join(' | ') + '</li>');
      });
      pendingCjkTokens = [];
    }

    definitions.forEach(function(item) {
      if (isCjkDefinition(item)) {
        pendingCjkTokens = pendingCjkTokens.concat(extractCjkTokens(item[0]));
        pendingCjkTokens = Array.from(new Set(pendingCjkTokens));
        return;
      }

      flushCjkTokens();
      html.push(renderDefinitionItem(item));
    });

    flushCjkTokens();
    return html.join('');
  }

  function isCjkDefinition(item) {
    return !item[1] && ZOO_CJK_RE.test(item[0]) && !/[A-Za-z]/.test(item[0]);
  }

  function extractCjkTokens(value) {
    return Array.from(new Set(String(value || '').match(ZOO_CJK_SEQUENCE_RE) || []));
  }

  function chunkCjkTokens(tokens) {
    var chunks = [];
    var current = [];
    var currentLength = 0;

    tokens.forEach(function(token) {
      var tokenLength = Array.from(token).length;
      var extraLength = current.length ? tokenLength + 3 : tokenLength;

      if (current.length && currentLength + extraLength > ZOO_SETTINGS.cjkDefinitionLineLength) {
        chunks.push(current);
        current = [];
        currentLength = 0;
        extraLength = tokenLength;
      }

      current.push(token);
      currentLength += extraLength;
    });

    if (current.length) {
      chunks.push(current);
    }

    return chunks;
  }

  function renderDefinitionItem(item) {
    var definition = escapeHtml(item[0]);
    var pos = escapeHtml(item[1]);
    var headword = item[2] ? escapeHtml(item[2]) : '';
    var prefix = headword ? '<span class="zoopdog-headword">' + headword + '</span>' : '';
    if (pos) {
      prefix += '<span class="zoopdog-pos">' + pos + '</span> ';
    }
    return '<li>' + prefix + definition + '</li>';
  }

  function main() {
    if (!document.body) {
      window.setTimeout(main, 50);
      return;
    }

    addStyle("__ZOOPDOG_CSS__");
    if (typeof zooProbeLocalMode === 'function') zooProbeLocalMode();
    if (typeof zooWireSelectionBar === 'function') zooWireSelectionBar();

    var highlighter = new Highlighter();
    var popup = new ResultPopup();
    var oldWord = null;

    popup.body.addEventListener('click', function(event) {
      var button = event.target && event.target.closest ? event.target.closest('[data-zd-action]') : null;
      if (!button) return;
      event.preventDefault();
      var action = button.getAttribute('data-zd-action');
      var vi = button.getAttribute('data-zd-vi') || '';
      if (action === 'add-nom') {
        zooOpenNomModal(vi);
      } else if (action === 'set-order') {
        zooOpenNomOrderModal(vi);
      }
    });

    function clearActiveResult() {
      highlighter.off();
      popup.hide();
    }

    function mainListener(event, clearOnMiss) {
      if (popup.locked || isExcludedTarget(event.target)) {
        return true;
      }

      var mouse = getEventPoint(event);
      if (!mouse) {
        return true;
      }

      var origin = getWordAndContext(mouse);
      var element = document.elementFromPoint(mouse.x, mouse.y);

      // `origin.atPoint` means the word was found by testing which text the
      // pointer falls inside, so cross-checking it against elementFromPoint
      // would only reject it: a search result card lays a link-shaped click
      // target over the whole row, and that overlay -- what elementFromPoint
      // answers with -- does not contain the line being hovered at all,
      // which is why those rows never showed a popup.
      if (!origin || !origin.word ||
          (!origin.atPoint && !elementContainsTextNode(element, origin.node))) {
        if (clearOnMiss) {
          clearActiveResult();
        }
        return true;
      }

      // Checked before clearing: a multi-word match's highlight rect covers
      // every word in the phrase (e.g. "một câu" also covers "câu"), so the
      // mouse can sit over a *different* word than the one that produced the
      // current match without ever leaving that rect. Comparing words here,
      // instead of gating on the rect the way `mouseout` below does, is what
      // lets hovering onto "câu" re-look-up and find "câu nói" instead of
      // getting stuck on "một câu". Same word: nothing to do, and skipping
      // the clear/reshow keeps the popup from flickering while it sits still.
      if (origin.word === oldWord) {
        return true;
      }

      clearActiveResult();
      oldWord = origin.word;
      var lookup = lookupContext(origin.context);
      if (!lookup) {
        window.setTimeout(function() {
          oldWord = null;
        }, ZOO_SETTINGS.oldWordResetMs);
        return true;
      }

      highlighter.on(origin.node, origin.begin, lookup.wordCount);
      popup.populate(lookup.results);
      popup.show(highlighter.highlights[0] || {
        left: mouse.x,
        right: mouse.x,
        top: mouse.y,
        bottom: mouse.y
      });

      window.setTimeout(function() {
        oldWord = null;
      }, ZOO_SETTINGS.oldWordResetMs);

      return true;
    }

    window.addEventListener('resize', function() {
      highlighter.resize();
      clearActiveResult();
    });

    function insidePopup(target) {
      return !!(target && target.nodeType === Node.ELEMENT_NODE &&
        target.closest('#zoopdog-userscript-popup'));
    }

    var lastTouchTime = 0;
    var touchMoved = false;
    var pointerTouchMoved = false;

    // Capture-phase so a scroll inside a nested scrollable container is seen
    // too (those don't bubble a 'scroll' event to window). But capture also
    // means this sees a scroll from *any* scrollable element on the page --
    // including ones with nothing to do with the highlighted word, such as an
    // auto-scrolling news ticker/carousel (e.g. jQuery SimplyScroll's
    // `.simply-scroll-clip`) that fires its own 'scroll' event dozens of
    // times a second purely from its own animation. Reacting to those
    // dismissed the popup within tens of milliseconds of ever showing it, on
    // any page carrying such a widget -- the "just blinks, can't show" bug.
    // Only a scroll of the document itself, or of a container the
    // highlighted word actually sits inside, can have moved that word.
    window.addEventListener('scroll', function(event) {
      var target = event.target;
      if (target && target !== document && target !== window && target !== document.documentElement &&
          highlighter.node && !zdContains(target, highlighter.node)) {
        return;
      }
      clearActiveResult();
    }, true);
    // `mouseout` bubbles, so this fires at every boundary between inline
    // boxes -- and a Nôm-annotated page is made of those, one <ruby> per
    // word, each often inside a link inside a card. Crossing one of them
    // while the pointer is still inside the word that is showing is not the
    // mouse leaving anything: the clear hid the popup a frame after it
    // appeared, and the `oldWord` guard in mainListener then kept it from
    // coming back until the reset timer fired -- measured as visible/hidden
    // flipping every few hundred ms while the pointer sat on one word, which
    // is the flicker. Leaving the word, or the window, still clears.
    window.addEventListener('mouseout', function(event) {
      if (Date.now() - lastTouchTime <= 700) return;
      var point = getEventPoint(event);
      if (point && highlighter.highlights.length && mouseInRects(point, highlighter.highlights)) {
        return;
      }
      clearActiveResult();
    });

    function touchListener(event) {
      lastTouchTime = Date.now();
      if (touchMoved) {
        touchMoved = false;
        return true;
      }
      return mainListener(event, true);
    }

    function clickListener(event) {
      if (Date.now() - lastTouchTime < 700) {
        return true;
      }
      return mainListener(event, true);
    }

    if ('PointerEvent' in window) {
      window.addEventListener('pointerdown', function(event) {
        if (event.pointerType === 'touch') {
          lastTouchTime = Date.now();
          pointerTouchMoved = false;
        }
      }, {passive: true});

      window.addEventListener('pointermove', function(event) {
        if (event.pointerType === 'touch') {
          lastTouchTime = Date.now();
          // A finger dragging inside the popup is scrolling the popup's own
          // content, not the page -- dismissing it would make it unscrollable.
          if (insidePopup(event.target)) return;
          pointerTouchMoved = true;
          clearActiveResult();
          return;
        }

        if (event.pointerType === 'mouse' || event.pointerType === 'pen') {
          mainListener(event, false);
        }
      }, {passive: true});

      window.addEventListener('pointerup', function(event) {
        if (event.pointerType === 'touch') {
          lastTouchTime = Date.now();
        }

        if (event.pointerType === 'touch' && pointerTouchMoved) {
          pointerTouchMoved = false;
          return true;
        }
        mainListener(event, true);
      }, {passive: true});
    } else {
      window.addEventListener('mousemove', function(event) {
        mainListener(event, false);
      });

      window.addEventListener('touchstart', function() {
        touchMoved = false;
      }, {passive: true});

      window.addEventListener('touchmove', function(event) {
        if (insidePopup(event.target)) return;
        touchMoved = true;
        clearActiveResult();
      }, {passive: true, capture: true});

      window.addEventListener('touchend', touchListener, {passive: true});
      window.addEventListener('click', clickListener);
    }

    window.addEventListener('keydown', function(event) {
      if (event.which === 16) {
        highlighter.toggleLock();
        popup.toggleLock();
      }
    });
  }

  main();
})();
