'use strict';

// Reviewed package inventory for the Chrome extension distributable.
//
// This is the human-maintained source of truth for "what ships": every path here is a
// deliberate decision, not a directory scan. `plan.js` discovers the same file set
// independently by walking manifest -> HTML -> CSS references (plus the explicit dynamic
// resources below) and fails loudly (`inventory_drift`) if the discovered set and this list
// ever disagree, so an edit to the manifest or a page's markup forces a reviewed edit here
// too instead of silently changing what ships.
//
// Update this file whenever zd-extension/manifest.json, an HTML page, or a stylesheet starts
// or stops referencing a file.

// Statically discoverable files: reachable by following manifest fields, then <script src>/
// <link href> in the referenced HTML, then url(...) in the referenced CSS.
const STATIC_ENTRIES = Object.freeze([
  'manifest.json',
  'popup.html',
  'frame.html',
  'icon/icon16.png',
  'icon/icon19.png',
  'icon/icon76.png',
  'icon/icon96.png',
  'icon/icon128.png',
  'css/zoopdog.css',
  'css/zoopdog-frame.css',
  'css/zd-pron.css',
  'css/fonts/fonts.css',
  'css/fonts/CharisSIL-B.woff',
  'css/fonts/CharisSIL-BI.woff',
  'css/fonts/CharisSIL-I.woff',
  'css/fonts/CharisSIL-R.woff',
  'css/fonts/DejaVuSansMono-Bold-webfont.eot',
  'css/fonts/DejaVuSansMono-Bold-webfont.svg',
  'css/fonts/DejaVuSansMono-Bold-webfont.ttf',
  'css/fonts/DejaVuSansMono-Bold-webfont.woff',
  'css/fonts/DejaVuSansMono-webfont.eot',
  'css/fonts/DejaVuSansMono-webfont.svg',
  'css/fonts/DejaVuSansMono-webfont.ttf',
  'css/fonts/DejaVuSansMono-webfont.woff',
  'css/fonts/DejaVuSansMono_latin+latin-ext+cyrillic.eot',
  'css/fonts/DejaVuSansMono_latin+latin-ext+cyrillic.svg',
  'css/fonts/DejaVuSansMono_latin+latin-ext+cyrillic.ttf',
  'css/fonts/DejaVuSansMono_latin+latin-ext+cyrillic.woff',
  'js/background.js',
  'js/content.js',
  'js/frame.js',
  'js/highlighter.js',
  'js/popup.js',
  'js/showframe.js',
  'js/zd-browser-runtime.js',
  'js/zd-popup-protocol.js',
  'js/zd-pron-data.js',
  'js/zd-pron-drawtones.js',
  'js/zd-pron-functions.js',
  'js/zd-words.js',
  'js/lib/chroma.min.js',
  'js/lib/handlebars.min.js',
  // Declared directly in manifest.web_accessible_resources (not a glob), so it is discovered
  // as a static reference even though the file itself is generated -- see DYNAMIC_ENTRIES for
  // its undeclared sibling.
  'js/vnedict.json'
]);

// Dynamic resources: loaded at runtime via `chrome.runtime.getURL(...)`/`importScripts(...)`
// in js/background.js rather than declared in the manifest, an HTML page, or a stylesheet, so
// they are not discoverable by static reference scanning -- a JS static analyzer can't safely
// infer every dynamic path, so these are enumerated by hand instead. `js/vnedict.meta.json`
// and `js/vnedict.json` above are further generated by a build step
// (scripts/build-extension-vnedict-json.js) rather than hand-written, so they are gitignored
// and must exist at packaging time rather than being checked in; the other two dynamic
// entries are checked-in files.
const DYNAMIC_ENTRIES = Object.freeze([
  'js/vnedict.meta.json',
  'js/zd-dictionary-runtime.js',
  'js/lib/dexie.min.js'
]);

// Glob-style manifest references that expand to a directory listing rather than a single
// file. Each key is the manifest-declared prefix (as written in web_accessible_resources);
// the value is the directory (relative to the extension root) it expands to. Expansion is a
// sorted `fs.readdirSync`, so it is deterministic across runs on the same tree.
const DIRECTORY_GLOBS = Object.freeze({
  'css/fonts/*': 'css/fonts'
});

const ALL_ENTRIES = Object.freeze([...STATIC_ENTRIES, ...DYNAMIC_ENTRIES].sort());

module.exports = {
  STATIC_ENTRIES,
  DYNAMIC_ENTRIES,
  DIRECTORY_GLOBS,
  ALL_ENTRIES
};
